import { useState } from "react";
import { Building2, Loader2, ShieldAlert, X } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiRequest } from "@/lib/queryClient";
import { ToolResultActions } from "@/components/ToolResultActions";

type Profile = { organization: { ccn: string; facilityName: string; doingBusinessAs: string; city: string; state: string; ownership: string; yearsCertified: number | null }; quality: Array<{ name: string; displayScore: string; reportingPeriod: string }>; familyExperience: Array<{ name: string; displayScore: string; reportingPeriod: string }>; serviceArea: { count: number }; sources: Array<{ label: string; checkedAt: string }> };

export function MedicareComparePanel({ initialCcn = "" }: { initialCcn?: string }) {
  const [ccn, setCcn] = useState(initialCcn); const [profiles, setProfiles] = useState<Profile[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const add = async () => {
    if (!/^\d{6}$/.test(ccn)) return setError("Enter a six-digit hospice CCN.");
    if (profiles.some((profile) => profile.organization.ccn === ccn)) return setError("That hospice is already in the comparison.");
    if (profiles.length >= 3) return setError("Remove a hospice before adding another.");
    setLoading(true); setError("");
    try { const response = await apiRequest("GET", `/api/intelligence/hospice-profile?ccn=${ccn}`); const data = await response.json(); setProfiles((current) => [...current, data.profile]); setCcn(""); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "The hospice profile could not be loaded."); }
    finally { setLoading(false); }
  };
  return <div className="space-y-5" data-testid="medicare-provider-compare">
    <Card className="border-primary/20 bg-gradient-to-br from-primary/10 via-card to-card p-5 sm:p-7"><p className="text-[10px] font-black uppercase tracking-widest text-primary">Provider compare</p><h2 className="mt-2 text-2xl font-black text-foreground sm:text-3xl">Compare evidence, not just scores.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Add up to three verified CCNs. Each value keeps its reporting boundary, and unavailable evidence remains unavailable.</p></Card>
    <Card className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="flex-1 space-y-2"><Label htmlFor="compare-ccn">Hospice CCN</Label><Input id="compare-ccn" inputMode="numeric" value={ccn} onChange={(event) => setCcn(event.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="Six digits" onKeyDown={(event) => { if (event.key === "Enter") void add(); }} /></div><Button type="button" onClick={() => void add()} disabled={loading || profiles.length >= 3}>{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Building2 className="mr-2 h-4 w-4" />}Add provider</Button></div>{error ? <p className="mt-3 text-sm text-destructive" role="alert">{error}</p> : null}</Card>
    {profiles.length ? <><div className="overflow-x-auto rounded-3xl border border-border bg-card"><table className="w-full min-w-[720px] border-collapse text-left"><thead><tr className="border-b border-border bg-muted/40"><th className="p-4 text-xs font-black uppercase tracking-wider text-muted-foreground">Evidence</th>{profiles.map((profile) => <th key={profile.organization.ccn} className="p-4 align-top"><div className="flex justify-between gap-3"><span><span className="block text-sm font-black text-foreground">{profile.organization.doingBusinessAs || profile.organization.facilityName}</span><span className="mt-1 block text-xs font-normal text-muted-foreground">CCN {profile.organization.ccn} · {profile.organization.city}, {profile.organization.state}</span></span><button aria-label={`Remove ${profile.organization.facilityName}`} onClick={() => setProfiles((current) => current.filter((item) => item.organization.ccn !== profile.organization.ccn))} className="rounded-lg p-1 text-muted-foreground hover:bg-muted hover:text-foreground"><X className="h-4 w-4" /></button></div></th>)}</tr></thead><tbody>{[
      ["Ownership", (p: Profile) => p.organization.ownership || "Unavailable"], ["Years certified", (p: Profile) => p.organization.yearsCertified == null ? "Unavailable" : String(p.organization.yearsCertified)], ["Service ZIP codes", (p: Profile) => String(p.serviceArea.count)], ["Quality measures", (p: Profile) => `${p.quality.length} reported`], ["Family measures", (p: Profile) => `${p.familyExperience.length} reported`], ["Latest source check", (p: Profile) => p.sources[0]?.checkedAt ? new Date(p.sources[0].checkedAt).toLocaleDateString() : "Unavailable"],
    ].map(([label, value]) => <tr key={String(label)} className="border-b border-border last:border-0"><th className="p-4 text-sm font-bold text-foreground">{String(label)}</th>{profiles.map((profile) => <td key={profile.organization.ccn} className="p-4 text-sm font-semibold text-foreground">{(value as (p: Profile) => string)(profile)}</td>)}</tr>)}</tbody></table></div>{profiles.length >= 2 ? <ToolResultActions toolId="spartan-intelligence" title="Keep the comparison moving" description="Save this evidence set, then use Coach to challenge what the public data does and does not prove." saveResult={{ toolId: "spartan-intelligence", title: `Medicare provider comparison · ${profiles.map((item) => item.organization.ccn).join(" vs ")}`, kind: "intelligence_brief", value: JSON.stringify({ profiles, boundary: "Public CMS comparison. Missing measures are not scored as zero." }), input: { ccns: profiles.map((item) => item.organization.ccn) }, nextAction: { title: "Pressure-test the comparison with Coach", href: "/portal/coach" } }} actions={[{ id: "coach", label: "Challenge with Coach", href: "/portal/coach" }, { id: "my-work", label: "Open My Work", href: "/my-work" }]} testId="provider-compare-actions" /> : null}</> : <Card className="flex min-h-48 flex-col items-center justify-center border-dashed p-6 text-center"><ShieldAlert className="h-7 w-7 text-primary" /><h3 className="mt-3 font-black text-foreground">No providers selected</h3><p className="mt-1 text-sm text-muted-foreground">Start with a CCN from Market or Provider 360.</p></Card>}
  </div>;
}
