import { AsyncLocalStorage } from "node:async_hooks";
import OpenAI from "openai";
import { zodTextFormat } from "openai/helpers/zod";
import type { ZodType } from "zod";
import { isUsableOpenAiApiKey } from "./provider-config";
import {
  getSpartanAiTool,
  isClinicalTool,
  type AiToolSpec,
  type SpartanAiToolId,
} from "./registry";
import {
  outputSchema as territoryOutputSchema,
  type ToolInput as TerritoryInput,
} from "./tools/territory-account-discovery/schema";

export class SpartanAiToolError extends Error {
  constructor(
    readonly code: string,
    readonly status: number,
    message: string,
    readonly retryable = false,
  ) {
    super(message);
  }
}

export type ClinicalJurisdictionContext = {
  state: string;
  macRegion: string;
};

const clinicalJurisdictionStorage = new AsyncLocalStorage<ClinicalJurisdictionContext>();

export function runWithClinicalJurisdiction<T>(
  context: ClinicalJurisdictionContext,
  callback: () => T,
): T {
  return clinicalJurisdictionStorage.run(context, callback);
}

export function currentClinicalJurisdiction(): ClinicalJurisdictionContext | null {
  return clinicalJurisdictionStorage.getStore() ?? null;
}

export interface ToolRunOptions {
  apiKey?: string;
  client?: OpenAI;
  model?: string;
  requestId?: string;
  timeoutMs?: number;
  signal?: AbortSignal;
}

export interface SpartanAiToolResult {
  output: unknown;
  metadata: {
    toolId: SpartanAiToolId;
    toolVersion: string;
    model: string;
    promptVersion: string;
    requestId?: string;
    durationMs: number;
    safetyWarnings: readonly string[];
    humanReviewRequired: boolean;
    jurisdiction: ClinicalJurisdictionContext | null;
  };
}

const SPARTAN_VOICE_STANDARD = `You are Spartan Coaching.

Your voice is human, direct, confident, practical, and grounded in real hospice work. Write like an experienced hospice sales coach who respects the reader and understands the field.

Use plain language, natural contractions, short paragraphs, and specific next steps. Remove corporate filler, generic consultant language, and anything that sounds generated by software. Never use dashes of any kind in customer facing writing. Never use markdown heading symbols, template braces, fake names, fake links, fake signatures, or placeholders. Never mention artificial intelligence. Never invent facts, relationships, outcomes, clinical claims, sources, or personalization.

Make every result immediately useful. Sound calm and credible, not promotional. Clinical and compliance boundaries always take priority over style.`;

function modelForTool(tool: AiToolSpec, options: ToolRunOptions): string {
  if (options.model) return options.model;
  if (isClinicalTool(tool)) {
    return process.env.OPENAI_CLINICAL_MODEL ?? process.env.OPENAI_MODEL ?? "gpt-5";
  }
  return process.env.OPENAI_FAST_MODEL ?? "gpt-5-mini";
}

const MAX_INPUT_BYTES = 256 * 1024;
const FORBIDDEN_INPUT_KEYS = new Set(["__proto__", "prototype", "constructor"]);

export function isToolFeatureEnabled(
  tool: AiToolSpec,
  environment: NodeJS.ProcessEnv = process.env,
): boolean {
  const configured = environment[tool.featureFlag];
  if (configured === "true") return true;
  if (configured === "false") return false;
  return true;
}

function assertSafeInput(value: unknown): void {
  let serialized: string;
  try {
    serialized = JSON.stringify(value);
  } catch {
    throw new SpartanAiToolError(
      "INVALID_INPUT",
      400,
      "Tool input must be valid JSON.",
    );
  }
  if (Buffer.byteLength(serialized, "utf8") > MAX_INPUT_BYTES) {
    throw new SpartanAiToolError(
      "INPUT_TOO_LARGE",
      413,
      "Tool input exceeds the 256 KB safety limit.",
    );
  }

  const inspect = (current: unknown, depth: number): void => {
    if (depth > 20) {
      throw new SpartanAiToolError(
        "INPUT_TOO_DEEP",
        400,
        "Tool input contains excessive nesting.",
      );
    }
    if (!current || typeof current !== "object") return;
    for (const [key, child] of Object.entries(current)) {
      if (FORBIDDEN_INPUT_KEYS.has(key)) {
        throw new SpartanAiToolError(
          "UNSAFE_INPUT",
          400,
          "Tool input contains a forbidden object key.",
        );
      }
      inspect(child, depth + 1);
    }
  };
  inspect(value, 0);
}

function runTerritory(input: unknown): unknown {
  const parsed = getSpartanAiTool(
    "territory-account-discovery",
  )!.inputSchema.parse(input) as TerritoryInput;
  const allowed = new Set(
    parsed.facilityTypes.map((value) => value.toLowerCase()),
  );
  const seen = new Set<string>();
  const matchedFacilities = parsed.facilities.filter((facility) => {
    const type = String(
      facility.facilityType ?? facility.type ?? "",
    ).toLowerCase();
    const id = String(
      facility.placeId ?? facility.id ?? JSON.stringify(facility),
    );
    if (!allowed.has(type) || seen.has(id)) return false;
    seen.add(id);
    return true;
  });
  return territoryOutputSchema.parse({
    matchedFacilities,
    searchedZipCodes: parsed.zipCodes,
    summary: {
      matched: matchedFacilities.length,
      radiusMiles: parsed.radiusMiles,
      requestedTypes: parsed.facilityTypes,
    },
    implementationNote:
      "Deterministic filtering was applied to the supplied facility search results.",
  });
}

function mapProviderError(error: unknown): SpartanAiToolError {
  if (error instanceof SpartanAiToolError) return error;
  if (
    typeof error === "object" &&
    error !== null &&
    "name" in error &&
    error.name === "APIConnectionTimeoutError"
  ) {
    return new SpartanAiToolError(
      "PROVIDER_TIMEOUT",
      504,
      "AI service timed out.",
      true,
    );
  }
  if (
    error instanceof DOMException &&
    (error.name === "AbortError" || error.name === "TimeoutError")
  ) {
    return new SpartanAiToolError(
      error.name === "AbortError" ? "PROVIDER_CANCELLED" : "PROVIDER_TIMEOUT",
      error.name === "AbortError" ? 499 : 504,
      error.name === "AbortError"
        ? "AI request was cancelled."
        : "AI service timed out.",
      error.name !== "AbortError",
    );
  }
  const status =
    typeof error === "object" &&
    error !== null &&
    "status" in error &&
    typeof error.status === "number"
      ? error.status
      : 502;
  if (status === 401 || status === 403) {
    return new SpartanAiToolError(
      "PROVIDER_AUTH",
      503,
      "AI service authentication failed.",
    );
  }
  if (status === 429) {
    return new SpartanAiToolError(
      "PROVIDER_RATE_LIMITED",
      429,
      "AI service is busy. Try again shortly.",
      true,
    );
  }
  if (status === 408) {
    return new SpartanAiToolError(
      "PROVIDER_TIMEOUT",
      504,
      "AI service timed out.",
      true,
    );
  }
  return new SpartanAiToolError(
    "PROVIDER_FAILED",
    502,
    "AI service could not complete the request.",
    true,
  );
}

function jurisdictionInstruction(context: ClinicalJurisdictionContext): string {
  return [
    "Jurisdiction context for this member:",
    `State: ${context.state}`,
    `Medicare Administrative Contractor region: ${context.macRegion}`,
    "Use this jurisdiction only as contextual guidance. Do not invent local rules, coverage criteria, or source versions.",
    "When a conclusion depends on current jurisdiction-specific coverage or regulation, identify that dependency and require verification against the approved current source before use.",
  ].join("\n");
}

export async function runSpartanAiTool(
  toolId: string,
  input: unknown,
  options: ToolRunOptions = {},
): Promise<SpartanAiToolResult> {
  const started = Date.now();
  const tool = getSpartanAiTool(toolId);
  if (!tool) {
    throw new SpartanAiToolError(
      "TOOL_NOT_FOUND",
      404,
      "AI tool was not found.",
    );
  }
  if (!isToolFeatureEnabled(tool)) {
    throw new SpartanAiToolError("TOOL_DISABLED", 503, "AI tool is disabled.");
  }
  assertSafeInput(input);
  const parsed = tool.inputSchema.safeParse(input);
  if (!parsed.success) {
    throw new SpartanAiToolError(
      "INVALID_INPUT",
      400,
      "Tool input did not match the required schema.",
    );
  }

  const jurisdiction = isClinicalTool(tool) ? currentClinicalJurisdiction() : null;
  const model = tool.deterministic
    ? "deterministic-v1"
    : (options.model ?? process.env.OPENAI_MODEL ?? "gpt-5");
  const timeoutMs =
    options.timeoutMs ?? (isClinicalTool(tool) ? 120_000 : 90_000);
  const model = tool.deterministic ? "deterministic-v1" : modelForTool(tool, options);
  const timeoutMs = options.timeoutMs ?? (isClinicalTool(tool) ? 60_000 : 35_000);

  try {
    const output = tool.deterministic
      ? runTerritory(parsed.data)
      : await (async () => {
          const apiKey = options.apiKey ?? process.env.OPENAI_API_KEY;
          if (!options.client && !isUsableOpenAiApiKey(apiKey)) {
            throw new SpartanAiToolError(
              "PROVIDER_NOT_CONFIGURED",
              503,
              "AI service is not configured.",
            );
          }
          const client =
            options.client ??
            new OpenAI({
              apiKey,
              timeout: timeoutMs,
              maxRetries: 0,
            });
          const systemMessages = [
            { role: "system" as const, content: SPARTAN_VOICE_STANDARD },
            { role: "system" as const, content: tool.systemPrompt },
            ...(jurisdiction
              ? [{ role: "system" as const, content: jurisdictionInstruction(jurisdiction) }]
              : []),
          ];
          const response = await client.responses.parse(
            {
              model,
              store: false,
              reasoning: { effort: isClinicalTool(tool) ? "low" : "minimal" },
              max_output_tokens: isClinicalTool(tool) ? 4_000 : 2_400,
              input: [
                ...systemMessages,
                {
                  role: "user",
                  content: tool.buildPrompt(parsed.data as never),
                },
              ],
              text: {
                format: zodTextFormat(
                  tool.outputSchema as ZodType,
                  tool.id.replaceAll("-", "_"),
                ),
              },
            },
            {
              timeout: timeoutMs,
              signal: options.signal,
              headers: options.requestId
                ? { "X-Client-Request-Id": options.requestId }
                : undefined,
            },
          );
          if (!response.output_parsed) {
            throw new SpartanAiToolError(
              "INVALID_MODEL_OUTPUT",
              502,
              "AI returned an invalid structured response.",
              true,
            );
          }
          return tool.outputSchema.parse(response.output_parsed);
        })();

    return {
      output,
      metadata: {
        toolId: tool.id,
        toolVersion: tool.version,
        model,
        promptVersion: `${tool.id}-v1`,
        requestId: options.requestId,
        durationMs: Date.now() - started,
        safetyWarnings: tool.safetyWarnings,
        humanReviewRequired: tool.containsPhi,
        jurisdiction,
      },
    };
  } catch (error) {
    throw mapProviderError(error);
  }
}
