// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/SpartanCommandFilm.tsx": () => import("../components/mockups/SpartanCommandFilm.tsx"),
  "./components/mockups/SpartanCurrentHome.tsx": () => import("../components/mockups/SpartanCurrentHome.tsx"),
  "./components/mockups/SpartanFieldIntelligence.tsx": () => import("../components/mockups/SpartanFieldIntelligence.tsx"),
  "./components/mockups/SpartanPrivateHouse.tsx": () => import("../components/mockups/SpartanPrivateHouse.tsx")
};
