import { db } from './runtime';
export type DecisionStatus='Committed'|'In progress'|'Blocked'|'Complete'|'Deferred';
export type DecisionAction={providerCcn:string;recommendationKey:string;title:string;category:string;gate:string;priority:number;status:DecisionStatus;owner:string;dueDate:string;note:string;createdAt:string;updatedAt:string};
const statuses=new Set<DecisionStatus>(['Committed','In progress','Blocked','Complete','Deferred']);
const clean=(v:unknown,max:number)=>String(v??'').trim().slice(0,max);
const normalizeCcn=(v:unknown)=>{const s=String(v??'').replace(/\D/g,'');if(!s||s.length>6)throw new Error('A valid hospice CCN is required.');return s.padStart(6,'0');};
const table=(userId:string,providerCcn:string)=>`decision-actions:${userId}:${normalizeCcn(providerCcn)}`;
export async function listDecisionActions(userId:string,providerCcn:string){const page=await db.list<DecisionAction>(table(userId,providerCcn),{limit:200}),records=page.items.sort((a,b)=>{const done=(x:DecisionAction)=>x.status==='Complete'?1:0;return done(a)-done(b)||String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999'))||b.updatedAt.localeCompare(a.updatedAt);});return{records,truncated:Boolean(page.nextToken),warning:page.nextToken?'More than 200 execution decisions exist for this provider. The current view is limited to the first stored page.':''};}
export async function createDecisionAction(userId:string,input:unknown){const b=(input&&typeof input==='object'?input:{}) as Record<string,unknown>,providerCcn=normalizeCcn(b.providerCcn),recommendationKey=clean(b.recommendationKey,180),title=clean(b.title,220);if(!recommendationKey||!title)throw new Error('Recommendation key and title are required.');const page=await db.list<DecisionAction>(table(userId,providerCcn),{limit:200}),existing=page.items.find(x=>x.recommendationKey===recommendationKey&&x.status!=='Complete');if(existing)return existing;const now=new Date().toISOString(),rawStatus=clean(b.status,40) as DecisionStatus,status=statuses.has(rawStatus)?rawStatus:'Committed',dueDate=/^\d{4}-\d{2}-\d{2}$/.test(clean(b.dueDate,10))?clean(b.dueDate,10):'',record:DecisionAction={providerCcn,recommendationKey,title,category:clean(b.category,60)||'Strategy',gate:clean(b.gate,30)||'CONDITIONAL',priority:Math.max(0,Math.min(100,Number(b.priority)||0)),status,owner:clean(b.owner,120),dueDate,note:clean(b.note,1200),createdAt:now,updatedAt:now},[id]=await db.add(table(userId,providerCcn),[record]);if(!id)throw new Error('Unable to add decision to the execution queue.');return{id,...record};}
export async function updateDecisionAction(userId:string,id:string,input:unknown){const b=(input&&typeof input==='object'?input:{}) as Record<string,unknown>,providerCcn=normalizeCcn(b.providerCcn),t=table(userId,providerCcn),[existing]=await db.get<DecisionAction>(t,[id]);if(!existing)throw new Error('Decision action not found.');const rawStatus=clean(b.status,40) as DecisionStatus,status=statuses.has(rawStatus)?rawStatus:existing.status,dueRaw=clean(b.dueDate,10),dueDate=dueRaw&&/^\d{4}-\d{2}-\d{2}$/.test(dueRaw)?dueRaw:dueRaw?'':existing.dueDate,record:DecisionAction={...existing,status,owner:b.owner===undefined?existing.owner:clean(b.owner,120),dueDate,note:b.note===undefined?existing.note:clean(b.note,1200),updatedAt:new Date().toISOString()},[ok]=await db.update(t,[{id,record}]);if(!ok)throw new Error('Unable to update the execution decision.');return{id,...record};}
export async function deleteDecisionAction(userId:string,id:string,providerCcn:string){const[ok]=await db.delete(table(userId,providerCcn),[id]);return{deleted:Boolean(ok),id};}
