import JSZip from 'jszip';
import { readJsonCache, writeJsonCache } from './cache';
import { measureValue, numericValue } from './measure';
import { fingerprintBytes, fetchBytesWithRetry, fetchJsonWithRetry, fetchTextWithRetry } from './http';
import { percentileRank } from './scoring';
import { buildHospiceOperatingModel } from './hcrisModel';

type Row = Record<string, unknown>;
type Crosswalk = Record<string, [string, string, number]>;
type CountyAdjacency = Record<string, string[]>;
type HReport = {
  reportRecordNumber: string;
  providerNumber: string;
  npi: string;
  statusCode: string;
  fiscalBegin: string;
  fiscalEnd: string;
  processed: string;
  initialReport: string;
  lastReport: string;
  controlType: string;
};

const SSVI_URL = 'https://www.cms.gov/files/zip/ssvi.zip';
const HCRIS_REPORTS_URL = 'https://downloads.cms.gov/Files/hcris/HOSPC14-REPORTS.zip';
const HCRIS_ALL_URL = 'https://downloads.cms.gov/Files/hcris/HOSPC14-ALL-YEARS.zip';
const CENSUS_ZCTA_COUNTY_URL = 'https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/tab20_zcta520_county20_natl.txt';
const CENSUS_COUNTY_ADJACENCY_URL = 'https://www2.census.gov/geo/docs/reference/county_adjacency/county_adjacency2025.txt';
const PDC = 'https://data.cms.gov/provider-data/api/1/datastore/query';
const HOSPICE_ZIP = '95rg-2usp';

const text = (value: unknown) => String(value ?? '').trim();
const nk = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, '');
const ccn = (value: unknown) => text(value).replace(/\D/g, '').slice(0, 6).padStart(6, '0');
const safeNumber = numericValue;

const xmlDecode = (value: string) => value.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'");
function columnIndex(ref: string) { const match = ref.match(/[A-Z]+/i)?.[0]?.toUpperCase() || 'A'; let value = 0; for (const char of match) value = value * 26 + char.charCodeAt(0) - 64; return value - 1; }
function sharedStrings(xml: string) { return [...xml.matchAll(/<si[\s\S]*?<\/si>/g)].map((match) => [...match[0].matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)].map((item) => xmlDecode(item[1])).join('')); }
function worksheetRows(xml: string, shared: string[]) { const rows: unknown[][] = []; for (const rowMatch of xml.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)) { const row: unknown[] = []; for (const cellMatch of rowMatch[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)) { const attrs = cellMatch[1], body = cellMatch[2], ref = attrs.match(/\br="([^"]+)"/)?.[1] || '', type = attrs.match(/\bt="([^"]+)"/)?.[1] || '', raw = body.match(/<v>([\s\S]*?)<\/v>/)?.[1] ?? body.match(/<t[^>]*>([\s\S]*?)<\/t>/)?.[1] ?? '', index = columnIndex(ref); row[index] = type === 's' ? shared[Number(raw)] ?? '' : xmlDecode(raw); } rows.push(row); } return rows; }
async function workbookTables(bytes: Uint8Array) { const zip = await JSZip.loadAsync(bytes), sharedFile = zip.file('xl/sharedStrings.xml'), shared = sharedFile ? sharedStrings(await sharedFile.async('string')) : [], workbook = await zip.file('xl/workbook.xml')?.async('string'); if (!workbook) throw new Error('SSVI workbook.xml not found'); const relationships = await zip.file('xl/_rels/workbook.xml.rels')?.async('string') || '', targets = new Map<string, string>(); for (const match of relationships.matchAll(/<Relationship[^>]*Id="([^"]+)"[^>]*Target="([^"]+)"/g)) targets.set(match[1], match[2]); const output = new Map<string, unknown[][]>(); for (const match of workbook.matchAll(/<sheet[^>]*name="([^"]+)"[^>]*r:id="([^"]+)"/g)) { const name = xmlDecode(match[1]), target = targets.get(match[2]); if (!target) continue; const path = target.startsWith('/') ? target.slice(1) : `xl/${target.replace(/^\.\//, '')}`, file = zip.file(path); if (file) output.set(name, worksheetRows(await file.async('string'), shared)); } return output; }
function objectsFromRows(rows: unknown[][]) { let headerIndex = -1; for (let index = 0; index < Math.min(20, rows.length); index += 1) if (rows[index].some((cell) => /\bccn\b|certification number/i.test(text(cell)))) { headerIndex = index; break; } if (headerIndex < 0) return [] as Row[]; const previous = rows[headerIndex - 1] || [], current = rows[headerIndex] || [], headers: string[] = []; let group = ''; for (let index = 0; index < Math.max(previous.length, current.length); index += 1) { if (text(previous[index])) group = text(previous[index]); const header = text(current[index]) || `Column ${index + 1}`; headers[index] = /ccn|certification number/i.test(header) || !group ? header : `${group} ${header}`; } return rows.slice(headerIndex + 1).map((row) => { const output: Row = {}; headers.forEach((header, index) => { if (row[index] !== undefined && text(row[index]) !== '') output[header] = row[index]; }); return output; }).filter((row) => Object.keys(row).length); }
function objField(row: Row, sets: string[][]) { for (const tokens of sets) { const hit = Object.keys(row).find((key) => tokens.every((token) => nk(key).includes(nk(token)))); if (hit) return row[hit]; } return undefined; }
function providerId(row: Row) { return ccn(objField(row, [['ccn'], ['certification', 'number'], ['provider', 'number']])); }
function compactFields(row: Row, max = 32) { return Object.entries(row).filter(([key, value]) => text(value) && !/ccn|certification number|provider number|provider name|facility name/i.test(key)).slice(0, max).map(([label, value]) => ({ label, raw: text(value), measure: measureValue(value) })); }

let ssviMemory: Map<string, any> | null = null;
let ssviMeta: any = null;
let ssviLoad: Promise<Map<string, any>> | null = null;
async function ensureSsvi(force = false) {
  if (force) { ssviMemory = null; ssviMeta = null; ssviLoad = null; }
  if (ssviMemory) return ssviMemory;
  if (ssviLoad) return ssviLoad;
  ssviLoad = (async () => {
    const outerBytes = await fetchBytesWithRetry(SSVI_URL, { timeout: 45000, retries: 2 }), fingerprint = fingerprintBytes(outerBytes), outer = await JSZip.loadAsync(outerBytes), xlsxFile = Object.values(outer.files).find((file) => !file.dir && /\.xlsx$/i.test(file.name));
    if (!xlsxFile) throw new Error('CMS SSVI workbook not found inside ssvi.zip');
    const tables = await workbookTables(await xlsxFile.async('uint8array')), entries = [...tables.entries()], sheet = (pattern: RegExp) => entries.find(([name]) => pattern.test(name));
    const totalSheet = sheet(/total.*ssvi.*score/i), data25Sheet = sheet(/fy\s*2025.*data/i), comp25Sheet = sheet(/fy\s*2025.*scoring.*component/i), data24Sheet = sheet(/fy\s*2024.*data/i), comp24Sheet = sheet(/fy\s*2024.*scoring.*component/i);
    if (!totalSheet || !data25Sheet || !comp25Sheet || !data24Sheet || !comp24Sheet) throw new Error('SSVI schema validation failed: one or more required FY2024/FY2025 sheets are missing');
    const total = objectsFromRows(totalSheet[1]), d25Rows = objectsFromRows(data25Sheet[1]), c25Rows = objectsFromRows(comp25Sheet[1]), d24Rows = objectsFromRows(data24Sheet[1]), c24Rows = objectsFromRows(comp24Sheet[1]);
    if (total.length < 1000) throw new Error(`SSVI schema validation failed: only ${total.length} provider rows parsed`);
    const by = (rows: Row[]) => new Map<string, Row>(rows.map((row): [string, Row] => [providerId(row), row]).filter(([id]) => /^\d{6}$/.test(id)));
    const totals = by(total), d25 = by(d25Rows), c25 = by(c25Rows), d24 = by(d24Rows), c24 = by(c24Rows);
    const scoreFor = (row: Row, year: '2025' | '2024') => safeNumber(objField(row, [[year, 'total', 'score'], [`fy${year}`, 'total', 'score']]));
    const valid25 = total.map((row) => scoreFor(row, '2025')).filter((value): value is number => value !== null), stateScores = new Map<string, number[]>();
    for (const row of total) { const state = text(objField(row, [['state']])), score = scoreFor(row, '2025'); if (state && score !== null) stateScores.set(state, [...(stateScores.get(state) || []), score]); }
    if (valid25.length < 1000) throw new Error('SSVI schema validation failed: insufficient FY2025 reportable score values');
    const map = new Map<string, any>(), ids = new Set([...totals.keys(), ...d25.keys(), ...c25.keys(), ...d24.keys(), ...c24.keys()]);
    for (const id of ids) {
      if (!/^\d{6}$/.test(id)) continue;
      const totalRow = totals.get(id) || {}, row = Object.keys(totalRow).length ? totalRow : d25.get(id) || c25.get(id) || d24.get(id) || c24.get(id) || {}, state = text(objField(row, [['state']])), y25 = Object.keys(totalRow).length ? scoreFor(totalRow, '2025') : null, y24 = Object.keys(totalRow).length ? scoreFor(totalRow, '2024') : null;
      const components = (componentRow: Row | undefined) => componentRow ? compactFields(componentRow, 40) : [];
      const data = (dataRow: Row | undefined) => dataRow ? compactFields(dataRow, 40) : [];
      const nat = percentileRank(valid25, y25), statePct = percentileRank(stateScores.get(state) || [], y25), band = nat === null ? 'Not reportable' : nat >= 90 ? 'High variation' : nat >= 75 ? 'Elevated variation' : nat >= 25 ? 'Typical range' : 'Low variation';
      const findComponent = (items: ReturnType<typeof compactFields>, patterns: RegExp[]) => items.find((item) => patterns.some((p) => p.test(item.label)))?.measure.value ?? null;
      const comp25 = components(c25.get(id)), comp24 = components(c24.get(id));
      map.set(id, { ccn: id, providerName: text(objField(row, [['provider', 'name'], ['facility', 'name'], ['hospice', 'name']])), state, scoreReportable: y25 !== null, fy2025: { totalScore: y25, reportable: y25 !== null, reportabilityReason: y25 !== null ? 'CMS published a provider-level FY2025 total score.' : 'No provider-level FY2025 SSVI total score was reportable for this CCN.', nationalPercentile: nat, statePercentile: statePct, variationBand: band, utilizationScore: findComponent(comp25, [/utilization/i]), nonHospiceSpendingScore: findComponent(comp25, [/non.?hospice.*spend/i, /spend.*non.?hospice/i]), scoringComponents: comp25, dataFields: data(d25.get(id)) }, fy2024: { totalScore: y24, reportable: y24 !== null, reportabilityReason: y24 !== null ? 'CMS published a provider-level FY2024 total score.' : 'No provider-level FY2024 SSVI total score was reportable for this CCN.', scoringComponents: comp24, dataFields: data(d24.get(id)) }, change: y25 !== null && y24 !== null ? y25 - y24 : null } );
    }
    ssviMemory = map; ssviMeta = { fingerprint, providerCount: map.size, totalRows: total.length, reportable2025: valid25.length, sheets: [...tables.keys()] }; return map;
  })();
  try { return await ssviLoad; } finally { ssviLoad = null; }
}
export async function getSsviIntelligence(ccnRaw: string, force = false) { const id = ccn(ccnRaw), path = `cms-cache/ssvi-v4/${id}.json`; if (!force) { const cached = await readJsonCache<any>(path, 7 * 86400000); if (cached) return { ...cached.data, cache: { mode: 'persistent', ageMinutes: cached.ageMinutes } }; } try { const map = await ensureSsvi(force), row = map.get(id), result = row ? { ...row, available: true, schemaHealth: 'verified', source: 'CMS Service & Spending Variation Index FY2024/FY2025', sourceUrl: SSVI_URL, schema: ssviMeta, caveat: 'SSVI is a CMS service/spending variation and oversight signal. It is not a quality grade, fraud determination, patient-eligibility measure or proof of wrongdoing.' } : { ccn: id, available: false, scoreReportable: false, fy2025: { totalScore: null, reportable: false, reportabilityReason: 'No provider-level FY2025 SSVI evidence was resolved.' }, fy2024: { totalScore: null, reportable: false }, schemaHealth: 'verified', source: 'CMS Service & Spending Variation Index FY2024/FY2025', sourceUrl: SSVI_URL, schema: ssviMeta, caveat: 'Missing SSVI evidence is not scored as zero.' }; await writeJsonCache(path, result, { sourceVersion: ssviMeta?.fingerprint }); return { ...result, cache: { mode: 'refreshed', ageMinutes: 0 } }; } catch (error) { return { ccn: id, available: false, scoreReportable: false, schemaHealth: 'unavailable', error: error instanceof Error ? error.message : String(error), source: 'CMS Service & Spending Variation Index', sourceUrl: SSVI_URL, caveat: 'The source could not be validated. No replacement score was inferred.' }; } }

function csvLine(line: string, delimiter = ',') { const out: string[] = []; let value = '', quoted = false; for (let i = 0; i < line.length; i += 1) { const ch = line[i]; if (ch === '"') { if (quoted && line[i + 1] === '"') { value += '"'; i += 1; } else quoted = !quoted; } else if (ch === delimiter && !quoted) { out.push(value.trim()); value = ''; } else value += ch; } out.push(value.trim()); return out; }
let hcrisMemory: Map<string, HReport[]> | null = null, hcrisMeta: any = null, hcrisLoad: Promise<Map<string, HReport[]>> | null = null;
async function ensureHcrisReports(force = false) {
  if (force) { hcrisMemory = null; hcrisMeta = null; hcrisLoad = null; }
  if (hcrisMemory) return hcrisMemory;
  if (hcrisLoad) return hcrisLoad;
  hcrisLoad = (async () => {
    const bytes = await fetchBytesWithRetry(HCRIS_REPORTS_URL, { timeout: 60000, retries: 2 }), fingerprint = fingerprintBytes(bytes), zip = await JSZip.loadAsync(bytes), file = Object.values(zip.files).find((item) => !item.dir && /\.(csv|txt)$/i.test(item.name));
    if (!file) throw new Error('HCRIS Hospice Reports extract not found');
    const raw = await file.async('string'), lines = raw.split(/\r?\n/).filter(Boolean);
    if (lines.length < 1000) throw new Error(`HCRIS schema validation failed: only ${lines.length} report lines`);
    const delimiter = (lines[0]?.split('\t').length || 0) > (lines[0]?.split(',').length || 0) ? '\t' : ',', first = csvLine(lines[0], delimiter), hasHeader = first.some((item) => /PRVDR_NUM/i.test(item)), headers = hasHeader ? first : [], indexOf = (name: string, fallback: number) => hasHeader ? headers.findIndex((header) => nk(header) === nk(name)) : fallback;
    if (hasHeader) for (const required of ['RPT_REC_NUM', 'PRVDR_NUM', 'FY_END_DT']) if (indexOf(required, -1) < 0) throw new Error(`HCRIS schema validation failed: missing ${required}`);
    const map = new Map<string, HReport[]>();
    for (let i = hasHeader ? 1 : 0; i < lines.length; i += 1) { const fields = csvLine(lines[i], delimiter), provider = ccn(fields[indexOf('PRVDR_NUM', 2)]); if (!/^\d{6}$/.test(provider)) continue; const report: HReport = { reportRecordNumber: text(fields[indexOf('RPT_REC_NUM', 0)]), controlType: text(fields[indexOf('PRVDR_CTRL_TYPE_CD', 1)]), providerNumber: provider, npi: text(fields[indexOf('NPI', 3)]), statusCode: text(fields[indexOf('RPT_STUS_CD', 4)]), fiscalBegin: text(fields[indexOf('FY_BGN_DT', 5)]), fiscalEnd: text(fields[indexOf('FY_END_DT', 6)]), processed: text(fields[indexOf('PROC_DT', 7)]), initialReport: text(fields[indexOf('INITL_RPT_SW', 8)]), lastReport: text(fields[indexOf('LAST_RPT_SW', 9)]) }; map.set(provider, [...(map.get(provider) || []), report]); }
    if (map.size < 500) throw new Error(`HCRIS schema validation failed: only ${map.size} providers parsed`);
    for (const reports of map.values()) reports.sort((a, b) => (Date.parse(b.fiscalEnd) || 0) - (Date.parse(a.fiscalEnd) || 0));
    hcrisMemory = map; hcrisMeta = { providerCount: map.size, reportLines: lines.length, hasHeader, fingerprint }; return map;
  })();
  try { return await hcrisLoad; } finally { hcrisLoad = null; }
}
const hCoord = (value: string) => { const digits = value.replace(/\D/g, ''); if (!digits) return NaN; return digits.length >= 3 ? Number(digits) / 100 : Number(digits); };
async function hcrisOperatingDetail(report: HReport, force = false) { const path = `cms-cache/hcris-operating-v2/${report.providerNumber}-${report.reportRecordNumber}.json`; if (!force) { const cached = await readJsonCache<any>(path, 30 * 86400000); if (cached) return { ...cached.data, cache: { mode: 'persistent', ageMinutes: cached.ageMinutes } }; } const bytes = await fetchBytesWithRetry(HCRIS_ALL_URL, { timeout: 90000, retries: 1 }), zip = await JSZip.loadAsync(bytes), file = Object.values(zip.files).find((item) => !item.dir && /(nmrc|numeric)/i.test(item.name)); if (!file) throw new Error('HCRIS numeric extract not found in all-years archive'); const raw = await file.async('string'), escaped = report.reportRecordNumber.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), matches = raw.match(new RegExp('^"?' + escaped + '"?[,|\\t].*$', 'gm')) || []; if (!matches.length) throw new Error('HCRIS report record was not found in the numeric extract'); const coordinates = new Map<string, number>(), coordinateKey = (worksheet: string, line: number, column: number) => `${worksheet.toUpperCase()}|${line.toFixed(2)}|${column.toFixed(2)}`; for (const match of matches) { const delimiter = match.includes('\t') ? '\t' : match.includes('|') ? '|' : ',', fields = csvLine(match, delimiter), worksheet = text(fields[1]).toUpperCase(), line = hCoord(text(fields[2])), column = hCoord(text(fields[3])), value = safeNumber(fields[4]); if (worksheet && Number.isFinite(line) && Number.isFinite(column) && value !== null) coordinates.set(coordinateKey(worksheet, line, column), value); } const get = (worksheet: string, line: number, column: number) => coordinates.get(coordinateKey(worksheet, line, column)) ?? null, metrics = { totalRevenue: get('F200000', 26, 4), totalOperatingExpenses: get('F200000', 41, 2), netIncomeLoss: get('F200000', 42, 2) }; if (Object.values(metrics).every((value) => value === null)) throw new Error('HCRIS operating-model validation failed: expected F-2 coordinates were absent'); const operatingModel = buildHospiceOperatingModel(get, metrics), result = { ...metrics, netIncomePctOfRevenue: metrics.totalRevenue && metrics.netIncomeLoss !== null ? metrics.netIncomeLoss / metrics.totalRevenue * 100 : null, operatingModel, reportRecordNumber: report.reportRecordNumber, fiscalEnd: report.fiscalEnd, source: 'CMS HCRIS Hospice CMS-1984-14 numeric extract', caveat: 'Provider-reported CMS cost-report evidence. Derived operating ratios are screening and benchmarking measures, not EBITDA, valuation, cash flow or a formal MAC cap settlement.' }; await writeJsonCache(path, result); return { ...result, cache: { mode: 'refreshed', ageMinutes: 0 } }; }
export async function getHcrisIntelligence(ccnRaw: string, detail = false, force = false) { const id = ccn(ccnRaw), path = `cms-cache/hcris-report-v3/${id}.json`; let base: any = null; if (!force) { const cached = await readJsonCache<any>(path, 7 * 86400000); if (cached) base = { ...cached.data, cache: { mode: 'persistent', ageMinutes: cached.ageMinutes } }; } if (!base) { try { const map = await ensureHcrisReports(force), reports = map.get(id) || [], latest = reports.find((report) => /y|1|true/i.test(report.lastReport)) || reports[0] || null; base = { ccn: id, available: Boolean(latest), latest, reports: reports.slice(0, 12), reportCount: reports.length, costReportBasis: 'Freestanding hospice CMS-1984-14', source: 'CMS HCRIS Hospice CMS-1984-14 Reports', sourceUrl: HCRIS_REPORTS_URL, availableThrough: 'FY2025', schemaHealth: 'verified', schema: hcrisMeta, caveat: 'The dedicated CMS-1984-14 hospice cost-report extract applies to freestanding hospice reporting. Absence here is not proof that a hospital- or HHA-based hospice lacks cost-report data elsewhere.' }; await writeJsonCache(path, base, { sourceVersion: hcrisMeta?.fingerprint }); } catch (error) { base = { ccn: id, available: false, costReportBasis: 'Hospice-specific CMS-1984-14 report not resolved', schemaHealth: 'unavailable', error: error instanceof Error ? error.message : String(error), source: 'CMS HCRIS Hospice CMS-1984-14 Reports', sourceUrl: HCRIS_REPORTS_URL, caveat: 'No cost-report financial value is inferred when the source cannot be validated.' }; } } if (detail && base.latest) { try { return { ...base, detail: await hcrisOperatingDetail(base.latest, force) }; } catch (error) { return { ...base, detail: { available: false, error: error instanceof Error ? error.message : String(error), caveat: 'Detailed HCRIS operating-model extraction failed; no financial value was inferred.' } }; } } return base; }

let crosswalkMemory: Crosswalk | null = null, censusMeta: any = null;
function parseDelimitedTable(raw: string) { const lines = raw.split(/\r?\n/).filter(Boolean); if (!lines.length) return { headers: [] as string[], rows: [] as string[][] }; const delimiter = lines[0].includes('|') ? '|' : lines[0].includes('\t') ? '\t' : ',', headers = csvLine(lines[0], delimiter); return { headers, rows: lines.slice(1).map((line) => csvLine(line, delimiter)) }; }
function col(headers: string[], ...names: string[]) { for (const name of names) { const i = headers.findIndex((h) => nk(h) === nk(name)); if (i >= 0) return i; } return -1; }
async function ensureCrosswalk(force = false) { if (force) crosswalkMemory = null; if (crosswalkMemory) return crosswalkMemory; const raw = await fetchTextWithRetry(CENSUS_ZCTA_COUNTY_URL, { timeout: 45000, retries: 2 }), { headers, rows } = parseDelimitedTable(raw), zipI = col(headers, 'GEOID_ZCTA5_20', 'ZCTA5CE20'), stateI = col(headers, 'STATEFP20', 'STATE'), countyI = col(headers, 'COUNTYFP20', 'COUNTY'), nameI = col(headers, 'NAMELSAD_COUNTY_20', 'NAME_COUNTY_20', 'NAMELSAD'), areaI = col(headers, 'AREALAND_PART', 'AREALAND_PART20'); if (zipI < 0 || stateI < 0 || countyI < 0) throw new Error('Census ZCTA-to-county schema changed: required geography columns were not found'); const best = new Map<string, { fips: string; name: string; area: number; count: number }>(); for (const row of rows) { const zip = text(row[zipI]).padStart(5, '0'), fips = `${text(row[stateI]).padStart(2, '0')}${text(row[countyI]).padStart(3, '0')}`, name = nameI >= 0 ? text(row[nameI]) : fips, area = areaI >= 0 ? Number(row[areaI]) || 0 : 0, prior = best.get(zip); if (!prior || area > prior.area) best.set(zip, { fips, name, area, count: (prior?.count || 0) + 1 }); else prior.count += 1; } const out: Crosswalk = {}; for (const [zip, item] of best) out[zip] = [item.fips, item.name.replace(/ County$/i, ''), item.count]; if (Object.keys(out).length < 10000) throw new Error(`Census ZCTA-to-county validation failed: only ${Object.keys(out).length} ZCTAs parsed`); crosswalkMemory = out; censusMeta = { fingerprint: fingerprintBytes(new TextEncoder().encode(raw)), zctaCount: Object.keys(out).length, rowCount: rows.length }; return out; }
export async function resolveZctaCounties(zips: string[], force = false) { const map = await ensureCrosswalk(force), out: Record<string, { fips: string; name: string; multiCounty: boolean }> = {}; for (const raw of [...new Set(zips)]) { const zip = text(raw).replace(/\D/g, '').slice(0, 5), hit = map[zip]; if (hit) out[zip] = { fips: hit[0], name: hit[1], multiCounty: hit[2] > 1 }; } return out; }

async function pdcZip(conditions: Record<string, string>, limit = 1500, offset = 0) { const url = new URL(`${PDC}/${HOSPICE_ZIP}/0`); let i = 0; for (const [property, value] of Object.entries(conditions)) { url.searchParams.set(`conditions[${i}][property]`, property); url.searchParams.set(`conditions[${i}][value]`, value); url.searchParams.set(`conditions[${i}][operator]`, '='); i += 1; } url.searchParams.set('limit', String(Math.min(1500, limit))); url.searchParams.set('offset', String(offset)); const raw = await fetchJsonWithRetry(url.toString(), { timeout: 18000, retries: 2 }) as any, rows = (Array.isArray(raw?.results) ? raw.results : []) as Row[]; return { rows, count: Number(raw?.count ?? raw?.total ?? rows.length) || rows.length }; }
async function allProviderZips(id: string) { const first = await pdcZip({ cms_certification_number_ccn: id }, 1500, 0), rows = [...first.rows], target = Math.min(first.count, 5000); for (let o = 1500; o < target; o += 1500) { const part = await pdcZip({ cms_certification_number_ccn: id }, 1500, o); rows.push(...part.rows); if (part.rows.length < 1500) break; } return { rows, count: first.count, partial: first.count > rows.length }; }
async function competitorsForZip(zip: string) { const path = `cms-cache/service-geo-zip/${zip}.json`, cached = await readJsonCache<string[]>(path, 7 * 86400000); if (cached) return cached.data; const result = await pdcZip({ zip_code: zip }, 1500, 0), ids = [...new Set(result.rows.map((row) => text(row.cms_certification_number_ccn)).filter(Boolean))]; if (result.count <= 1500) await writeJsonCache(path, ids); return ids; }
export async function getServiceGeography(ccnRaw: string, force = false) { const id = ccn(ccnRaw), path = `cms-cache/service-geography-v4/${id}.json`; if (!force) { const cached = await readJsonCache<any>(path, 7 * 86400000); if (cached) return { ...cached.data, cache: { mode: 'persistent', ageMinutes: cached.ageMinutes } }; } try { const result = await allProviderZips(id), serviceZips = [...new Set(result.rows.map((row) => text(row.zip_code || row.zip || '')).filter(Boolean).map((zip) => zip.replace(/\D/g, '').slice(0, 5)).filter((zip) => /^\d{5}$/.test(zip)))].sort(), mapped = await resolveZctaCounties(serviceZips, force), countyMap = new Map<string, any>(); for (let i = 0; i < serviceZips.length; i += 10) { const batch = serviceZips.slice(i, i + 10), competition = await Promise.all(batch.map(async (zip) => ({ zip, ids: await competitorsForZip(zip) }))); for (const item of competition) { const geo = mapped[item.zip]; if (!geo) continue; const existing = countyMap.get(geo.fips) || { fips: geo.fips, name: geo.name, serviceZips: 0, competitorSet: new Set<string>(), multiCountyZctas: 0 }; existing.serviceZips += 1; item.ids.filter((candidate) => candidate !== id).forEach((candidate) => existing.competitorSet.add(candidate)); if (geo.multiCounty) existing.multiCountyZctas += 1; countyMap.set(geo.fips, existing); } } const counties = [...countyMap.values()].map((item) => ({ fips: item.fips, name: item.name, serviceZips: item.serviceZips, competitors: item.competitorSet.size, multiCountyZctas: item.multiCountyZctas })).sort((a, b) => b.serviceZips - a.serviceZips || a.name.localeCompare(b.name)), mappedZipCount = serviceZips.filter((zip) => mapped[zip]).length, mappingCoveragePct = serviceZips.length ? Math.round(mappedZipCount / serviceZips.length * 1000) / 10 : 0, output = { ccn: id, available: serviceZips.length > 0, serviceZipCount: serviceZips.length, mappedZipCount, mappingCoveragePct, counties, sourceCount: result.count, sourceRows: result.rows.length, partial: result.partial, schemaHealth: mappingCoveragePct >= 90 ? 'verified' : 'limited', source: 'CMS Hospice ZIP Data + U.S. Census 2020 ZCTA-to-county relationship', censusSchema: censusMeta, caveat: 'CMS service ZIPs are mapped through Census ZCTA relationships. ZCTAs are not identical to USPS ZIP geography. This observed footprint does not establish licensure, drive time, staffing radius, contractual access or patient eligibility.' }; await writeJsonCache(path, output); return { ...output, cache: { mode: 'refreshed', ageMinutes: 0 } }; } catch (error) { return { ccn: id, available: false, counties: [], serviceZipCount: 0, mappedZipCount: 0, mappingCoveragePct: 0, schemaHealth: 'unavailable', error: error instanceof Error ? error.message : String(error), caveat: 'Service geography could not be validated; no county footprint was inferred.' }; } }

let adjacencyMemory: CountyAdjacency | null = null, adjacencyMeta: any = null;
async function ensureAdjacency(force = false) { if (force) adjacencyMemory = null; if (adjacencyMemory) return adjacencyMemory; const raw = await fetchTextWithRetry(CENSUS_COUNTY_ADJACENCY_URL, { timeout: 45000, retries: 2 }), lines = raw.split(/\r?\n/).filter(Boolean), map: CountyAdjacency = {}; let anchor = ''; const fipsRe = /\b(\d{5})\b/; for (const line of lines) { const fields = line.split('\t').map((v) => v.replace(/^"|"$/g, '').trim()), first = fields.find((field) => fipsRe.test(field)), ids = fields.map((field) => field.match(fipsRe)?.[1]).filter((value): value is string => Boolean(value)); if (!ids.length) continue; if (ids.length >= 2) anchor = ids[0]; const target = ids.length >= 2 ? ids[1] : ids[0]; if (!anchor) anchor = target; if (target && target !== anchor) { map[anchor] = [...new Set([...(map[anchor] || []), target])]; map[target] = [...new Set([...(map[target] || []), anchor])]; } } if (Object.keys(map).length < 1000) throw new Error(`Census county adjacency validation failed: only ${Object.keys(map).length} county/equivalent rows parsed`); adjacencyMemory = map; adjacencyMeta = { fingerprint: fingerprintBytes(new TextEncoder().encode(raw)), countyCount: Object.keys(map).length, lineCount: lines.length }; return map; }
export async function getCountyAdjacency(fipsList: string[] = [], force = false) { try { const all = await ensureAdjacency(force), wanted = new Set(fipsList.filter((value) => /^\d{5}$/.test(value))), adjacency: CountyAdjacency = {}; if (wanted.size) for (const fips of wanted) adjacency[fips] = all[fips] || []; else Object.assign(adjacency, all); return { adjacency, countyCount: Object.keys(adjacency).length, source: 'U.S. Census Bureau 2025 County Adjacency File', schemaHealth: 'verified', schema: adjacencyMeta, caveat: 'County adjacency is geographic context, not proof that a hospice can legally or operationally serve an adjacent market.' }; } catch (error) { return { adjacency: {}, countyCount: 0, source: 'U.S. Census Bureau 2025 County Adjacency File', schemaHealth: 'unavailable', error: error instanceof Error ? error.message : String(error) }; } }

export async function getExternalSourceHealth(force = false) { const path = 'cms-cache/external-source-health-v3.json', previous = force ? null : await readJsonCache<any>(path, 18 * 3600000); if (previous) return { ...previous.data, cache: { mode: 'persistent', ageMinutes: previous.ageMinutes } }; const checks = await Promise.allSettled([ensureSsvi(force), ensureHcrisReports(force), ensureCrosswalk(force), ensureAdjacency(force)]), names = ['CMS SSVI', 'CMS HCRIS Hospice Reports', 'Census ZCTA-County', 'Census County Adjacency'], metas = [ssviMeta, hcrisMeta, censusMeta, adjacencyMeta], sources = checks.map((check, index) => check.status === 'fulfilled' ? { name: names[index], status: 'healthy', fingerprint: metas[index]?.fingerprint || '', detail: 'Source contract and schema parsed successfully.' } : { name: names[index], status: 'error', fingerprint: '', detail: check.reason instanceof Error ? check.reason.message : String(check.reason) }), overall = sources.some((source) => source.status === 'error') ? 'limited' : 'healthy', result = { checkedAt: new Date().toISOString(), overall, liveValidation: force, changedSources: [] as string[], sources, dataQuality: { status: overall, limitations: sources.filter((source) => source.status === 'error').map((source) => `${source.name}: ${source.detail}`) } }; await writeJsonCache(path, result); return { ...result, cache: { mode: 'refreshed', ageMinutes: 0 } }; }
