export type FetchOptions={timeout?:number;retries?:number;headers?:Record<string,string>};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const retryable=(status:number)=>status===408||status===425||status===429||status>=500;
async function request(url:string,o:FetchOptions={}){const timeout=o.timeout??20000,retries=o.retries??2;let last='';for(let attempt=0;attempt<=retries;attempt++){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{signal:ctl.signal,headers:o.headers});if(!r.ok){last=`${r.status} ${r.statusText}`;if(attempt<retries&&retryable(r.status)){await wait(Math.min(2500,350*Math.pow(2,attempt)+Math.random()*180));continue;}throw new Error(`Upstream ${last}`);}return r;}catch(e){last=e instanceof Error?e.message:String(e);if(attempt>=retries)throw new Error(`Upstream request failed: ${last}`);await wait(Math.min(2500,350*Math.pow(2,attempt)+Math.random()*180));}finally{clearTimeout(timer);}}throw new Error(`Upstream request failed: ${last}`);}
export async function fetchJsonWithRetry(url:string,o:FetchOptions={}){const r=await request(url,{...o,headers:{accept:'application/json',...(o.headers||{})}}),body=await r.text();try{return JSON.parse(body);}catch{throw new Error(`Upstream returned invalid JSON (${r.status}) from ${new URL(url).hostname}`);}}
export async function fetchTextWithRetry(url:string,o:FetchOptions={}){const r=await request(url,{...o,headers:{accept:'text/plain,*/*',...(o.headers||{})}});return r.text();}
export async function fetchBytesWithRetry(url:string,o:FetchOptions={}){const r=await request(url,{...o,headers:{accept:'application/zip,application/octet-stream,*/*',...(o.headers||{})}});return new Uint8Array(await r.arrayBuffer());}
export function fingerprintBytes(bytes:Uint8Array){let h=2166136261;for(let i=0;i<bytes.length;i++){h^=bytes[i];h=Math.imul(h,16777619);}return`${bytes.length.toString(36)}-${(h>>>0).toString(36)}`;}
export function fingerprintText(value:string){return fingerprintBytes(new TextEncoder().encode(value));}
