import { storage } from './runtime';
import { captureProviderSnapshot } from './warehouse';
import { createChangeAlerts } from './alerts';
import { getWatchersForProvider } from './watchlist';
import type { SnapshotChange } from './change';
type MonitorDefinition={ccn:string;state:string;label?:string;updatedAt?:string};type PendingDelivery={ccn:string;state:string;label:string;changes:SnapshotChange[];nextToken:string;createdAt:string};
const checkpointPath='monitoring/checkpoint.json',pendingPrefix='monitoring/pending-alerts/';const statusPath=(ccn:string)=>`monitoring/status/${ccn}.json`,pendingPath=(ccn:string)=>`${pendingPrefix}${ccn}-${Date.now()}.json`;
async function writeStatus(ccn:string,status:Record<string,unknown>){const[ok]=await storage.write([{path:statusPath(ccn),content:JSON.stringify({ccn,...status}),contentType:'application/json'}]);if(!ok)console.warn('monitor_status_write_failed',ccn);}
async function queuePending(def:PendingDelivery){const[ok]=await storage.write([{path:pendingPath(def.ccn),content:JSON.stringify(def),contentType:'application/json'}]);if(!ok)console.warn('monitor_alert_backlog_write_failed',def.ccn);return ok;}
async function processPendingAlertDeliveries(limit=3){const page=await storage.list({prefix:pendingPrefix,limit:Math.max(1,Math.min(10,limit))}),files=page.paths.length?await storage.read(page.paths):[],results=[] as any[];for(const file of files){if(!file.content)continue;try{const def=JSON.parse(file.content) as PendingDelivery,pageWatchers=await getWatchersForProvider(def.ccn,def.nextToken),alerts=await createChangeAlerts(def.ccn,def.label,def.state,def.changes,pageWatchers.watchers);if(pageWatchers.nextToken){const[ok]=await storage.write([{path:file.path,content:JSON.stringify({...def,nextToken:pageWatchers.nextToken}),contentType:'application/json'}]);if(!ok)throw new Error('Unable to checkpoint pending alert delivery.');}else await storage.delete([file.path]);results.push({ccn:def.ccn,created:alerts.created,pushSent:alerts.pushSent,more:Boolean(pageWatchers.nextToken)});}catch(e){results.push({path:file.path,error:e instanceof Error?e.message:String(e)});}}return{processed:results.length,remaining:Boolean(page.nextToken)||results.some(r=>r.more),failed:results.filter(r=>r.error).length,results};}
export async function processOneMonitoredProvider(ccn:string,state:string,label:string,notify=true){const checkedAt=new Date().toISOString();try{const result=await captureProviderSnapshot(ccn,state,false),watchers=await getWatchersForProvider(ccn),canonicalLabel=result.snapshot?.provider?.name||label||ccn,canonicalState=result.snapshot?.provider?.state||state;let alertResult={created:0,pushSent:0},backlogQueued=false;if(notify&&result.captured&&result.changes.length){alertResult=await createChangeAlerts(ccn,canonicalLabel,canonicalState,result.changes,watchers.watchers);if(watchers.nextToken)backlogQueued=await queuePending({ccn,state:canonicalState,label:canonicalLabel,changes:result.changes,nextToken:watchers.nextToken,createdAt:checkedAt});}await writeStatus(ccn,{lastCheckedAt:checkedAt,lastChangeAt:result.captured&&result.changes.length?checkedAt:undefined,lastStatus:result.status,changes:result.changes.length,alertsCreated:alertResult.created,pushSent:alertResult.pushSent,alertBacklog:backlogQueued});return{ccn,ok:true,status:result.status,changes:result.changes.length,...alertResult,alertBacklog:backlogQueued};}catch(e){const message=e instanceof Error?e.message:String(e);await writeStatus(ccn,{lastCheckedAt:checkedAt,lastStatus:'error',lastError:message});console.warn('provider_monitor_failed',ccn,message);return{ccn,ok:false,error:message};}}
export async function processWatchedProviderBatch(limit=8){let pending:any={processed:0,remaining:false,failed:0};try{pending=await processPendingAlertDeliveries(3);}catch(e){pending={processed:0,remaining:true,failed:1,error:e instanceof Error?e.message:String(e)};console.warn('pending_alert_delivery_failed',pending.error);}let nextToken:string|undefined;try{const[f]=await storage.read([checkpointPath]);if(f?.content){const parsed=JSON.parse(f.content) as{nextToken?:string|null};nextToken=parsed.nextToken||undefined;}}catch{}let page;try{page=await storage.list({prefix:'monitoring/providers/',limit:Math.max(1,Math.min(25,limit)),nextToken});}catch(e){if(nextToken){nextToken=undefined;page=await storage.list({prefix:'monitoring/providers/',limit:Math.max(1,Math.min(25,limit))});}else throw e;}const files=page.paths.length?await storage.read(page.paths):[],results=[] as any[];for(const file of files){if(!file.content)continue;try{const def=JSON.parse(file.content) as MonitorDefinition;results.push(await processOneMonitoredProvider(def.ccn,def.state,def.label||def.ccn,true));}catch(e){results.push({path:file.path,ok:false,error:e instanceof Error?e.message:String(e)});}}const checkpoint={nextToken:page.nextToken||null,lastRun:new Date().toISOString(),processed:results.length},[ok]=await storage.write([{path:checkpointPath,content:JSON.stringify(checkpoint),contentType:'application/json'}]);if(!ok)console.warn('monitor_checkpoint_write_failed');return{processed:results.length,changed:results.filter(r=>r.ok&&r.changes>0).length,failed:results.filter(r=>!r.ok).length,nextToken:Boolean(page.nextToken),pending,results};}
