import { storage } from './runtime';
import { buildAdvancedIntelligence } from './cmsIntelligence';
import { getHcrisIntelligence, getServiceGeography, getSsviIntelligence } from './externalIntelligence';
import { getSourceHealth } from './sourceHealth';
import { compareSnapshots } from './change';
type AnyRow=Record<string,any>;
export type ProviderSnapshot={schemaVersion:'2'|'3';capturedAt:string;fingerprint:string;ccn:string;state:string;provider:{name:string;city:string;state:string};metrics:Record<string,unknown>;sourceLineage:AnyRow[];dataQuality:AnyRow};
const cleanCcn=(v:string)=>{const x=String(v||'').replace(/\D/g,'').slice(0,6).padStart(6,'0');if(!/^\d{6}$/.test(x))throw new Error('A valid hospice CCN is required.');return x;};
const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');};
const benchmark=(intel:AnyRow,code:string,re?:RegExp)=>{const row=(intel?.benchmarks||[]).find((x:AnyRow)=>String(x.code||'')===code)||(re?(intel?.benchmarks||[]).find((x:AnyRow)=>re.test(String(x.label||''))):null);return row?.provider??null;};
const paths=(ccn:string)=>({latest:`warehouse/provider/${ccn}/latest.json`,index:`warehouse/provider/${ccn}/index.json`});
const inFlight=new Map<string,Promise<any>>();
async function readJson<T>(path:string){const[f]=await storage.read([path]);if(!f?.content)return null;try{return JSON.parse(f.content) as T;}catch{return null;}}
async function capture(ccnRaw:string,stateRaw='',force=false){const ccn=cleanCcn(ccnRaw),state=String(stateRaw||'').toUpperCase(),[intel,ssvi,hcris,geo,health]=await Promise.all([buildAdvancedIntelligence(ccn,state,force),getSsviIntelligence(ccn,false),getHcrisIntelligence(ccn,false,false),getServiceGeography(ccn,false),getSourceHealth(false)]),topThreat=(intel.threats||[])[0]||null,metrics={adc:intel.financial?.adc??null,beneficiaries:intel.financial?.beneficiaries??null,payment:intel.financial?.payment??null,serviceZipCount:intel.serviceArea?.focusZipCount??null,countyFootprint:geo?.counties?.length??null,mappingCoveragePct:geo?.mappingCoveragePct??null,cahpsStar:benchmark(intel,'SUMMARY_STAR_RATING'),recommendPct:benchmark(intel,'RECOMMEND_TBV'),timelyHelpPct:benchmark(intel,'TIMELY_CARE_TBV'),hci:benchmark(intel,'',/Hospice Care Index/i),ssvi2025:ssvi?.fy2025?.totalScore??null,topThreatScore:topThreat?.threatScore??null,topThreatSharedZips:topThreat?.shared??null,topThreatCcn:topThreat?.ccn||'',relatedEnrollments:intel.enterprise?.totalRelatedEnrollments??intel.enterprise?.relatedEnrollments?.length??null,legalName:intel.enterprise?.legalName||'',hcrisFiscalEnd:hcris?.latest?.fiscalEnd||''},sourceLineage=(health?.sources||[]).map((s:AnyRow)=>({name:s.name,status:s.status,fingerprint:s.fingerprint||'',changed:Boolean(s.changed)})),base={schemaVersion:'3' as const,capturedAt:new Date().toISOString(),ccn,state:intel.provider?.state||state,provider:{name:intel.provider?.name||ccn,city:intel.provider?.city||'',state:intel.provider?.state||state},metrics,sourceLineage,dataQuality:{core:intel.dataQuality||{},ssvi:ssvi?.schemaHealth||'unknown',hcris:hcris?.schemaHealth||'unknown',geography:geo?.schemaHealth||'unknown'}},fingerprint=hash(JSON.stringify({ccn:base.ccn,state:base.state,metrics:base.metrics,sourceLineage:base.sourceLineage})),current:ProviderSnapshot={...base,fingerprint},p=paths(ccn),previous=await readJson<ProviderSnapshot>(p.latest),changes=compareSnapshots(previous,current),existingIndex=await readJson<string[]>(p.index)||[];if(previous?.fingerprint===current.fingerprint)return{snapshot:previous,previous,changes:[],captured:false,historyCount:existingIndex.length||1,status:'no_change'};const historyPath=`warehouse/provider/${ccn}/history/${Date.now()}.json`,nextIndex=[historyPath,...existingIndex].slice(0,30),writes=await storage.write([{path:historyPath,content:JSON.stringify(current),contentType:'application/json'},{path:p.latest,content:JSON.stringify(current),contentType:'application/json'},{path:p.index,content:JSON.stringify(nextIndex),contentType:'application/json'}]);if(writes.some(ok=>!ok))throw new Error(`Provider snapshot write failed for CCN ${ccn}`);return{snapshot:current,previous,changes,captured:true,historyCount:nextIndex.length,status:previous?'changed':'baseline_created'};}
export async function captureProviderSnapshot(ccnRaw:string,stateRaw='',force=false){const ccn=cleanCcn(ccnRaw),key=`${ccn}:${force?'force':'cached'}`,existing=inFlight.get(key);if(existing)return existing;const task=capture(ccn,stateRaw,force).finally(()=>inFlight.delete(key));inFlight.set(key,task);return task;}
export async function getProviderHistory(ccnRaw:string){const ccn=cleanCcn(ccnRaw),p=paths(ccn),index=await readJson<string[]>(p.index)||[],recent=index.slice(0,30),files=recent.length?await storage.read(recent):[],snapshots=files.map(f=>{try{return f.content?JSON.parse(f.content) as ProviderSnapshot:null;}catch{return null;}}).filter((x):x is ProviderSnapshot=>Boolean(x)).sort((a,b)=>b.capturedAt.localeCompare(a.capturedAt)),latest=snapshots[0]||await readJson<ProviderSnapshot>(p.latest),changes=latest?compareSnapshots(snapshots[1]||null,latest):[],status=!latest?'no_baseline':snapshots.length<=1?'baseline_created':changes.length?'changed':'no_change';return{ccn,historyCount:index.length,snapshots,latest,changes,status};}
