import { db, storage } from './runtime';
export type WatchRecord={type:'provider';ccn:string;state:string;label:string;createdAt:string;providerWatcherId?:string};
type WatcherRecord={userId:string;watchId:string;state:string;label:string;createdAt:string};
type MonitorStatus={ccn:string;lastCheckedAt?:string;lastChangeAt?:string;lastStatus?:string;lastError?:string};
const table=(userId:string)=>`watchlist:${userId}`,watchersTable=(ccn:string)=>`provider-watchers:${ccn}`,monitorPath=(ccn:string)=>`monitoring/providers/${ccn}.json`,statusPath=(ccn:string)=>`monitoring/status/${ccn}.json`;
const ccn=(v:unknown)=>{const x=String(v??'').replace(/\D/g,'').slice(0,6).padStart(6,'0');if(!/^\d{6}$/.test(x))throw new Error('A valid provider CCN is required.');return x;};
async function registerWatcher(userId:string,record:WatchRecord&{id:string}){if(record.providerWatcherId)return record;const[providerWatcherId]=await db.add(watchersTable(record.ccn),[{userId,watchId:record.id,state:record.state,label:record.label,createdAt:record.createdAt} satisfies WatcherRecord]);if(!providerWatcherId)throw new Error('Unable to register provider monitor.');const monitor={ccn:record.ccn,state:record.state,label:record.label,updatedAt:new Date().toISOString()},[stored]=await storage.write([{path:monitorPath(record.ccn),content:JSON.stringify(monitor),contentType:'application/json'}]);if(!stored){await db.delete(watchersTable(record.ccn),[providerWatcherId]);throw new Error('Unable to register provider monitor.');}const updated={...record,providerWatcherId},[ok]=await db.update(table(userId),[{id:record.id,record:updated}]);if(!ok)throw new Error('Unable to finalize watchlist monitor registration.');return updated;}
export async function listWatchlist(userId:string,ccnFilter=''){const page=await db.list<WatchRecord>(table(userId),{limit:100}),migrated=[] as Array<WatchRecord&{id:string}>;for(const row of page.items){try{migrated.push(await registerWatcher(userId,row as WatchRecord&{id:string}));}catch{migrated.push(row as WatchRecord&{id:string});}}const filter=ccnFilter?ccn(ccnFilter):'',records=migrated.filter(r=>!filter||r.ccn===filter).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),statusFiles=records.length?await storage.read(records.map(r=>statusPath(r.ccn))):[],statuses=new Map<string,MonitorStatus>();statusFiles.forEach(f=>{if(!f.content)return;try{const s=JSON.parse(f.content) as MonitorStatus;statuses.set(s.ccn,s);}catch{}});return{records:records.map(r=>({...r,monitor:statuses.get(r.ccn)||null})),total:page.items.length,truncated:Boolean(page.nextToken),warning:page.nextToken?'Watchlist contains more than 100 records; only the first page is shown.':''};}
export async function addWatch(userId:string,input:unknown){const b=(input&&typeof input==='object'?input:{}) as Record<string,unknown>,id=ccn(b.ccn),existing=await listWatchlist(userId);const found=existing.records.find(r=>r.ccn===id);if(found)return found;if(existing.total>=100)throw new Error('Watchlist limit reached. Remove a provider before adding another.');const base:WatchRecord={type:'provider',ccn:id,state:String(b.state??'').toUpperCase().slice(0,2),label:String(b.label??id).trim().slice(0,180)||id,createdAt:new Date().toISOString()},[watchId]=await db.add(table(userId),[base]);if(!watchId)throw new Error('Unable to add provider to watchlist.');try{return await registerWatcher(userId,{id:watchId,...base});}catch(e){await db.delete(table(userId),[watchId]);throw e;}}
export async function getWatchById(userId:string,id:string){const[row]=await db.get<WatchRecord>(table(userId),[id]);return row?{id,...row}:null;}
export async function getWatchersForProvider(providerCcn:string,nextToken?:string){const page=await db.list<WatcherRecord>(watchersTable(ccn(providerCcn)),{limit:100,nextToken});return{watchers:page.items,truncated:Boolean(page.nextToken),nextToken:page.nextToken};}
export async function removeWatch(userId:string,id:string){const existing=await getWatchById(userId,id);if(!existing)return{deleted:false,id};const[ok]=await db.delete(table(userId),[id]);if(!ok)return{deleted:false,id};if(existing.providerWatcherId)await db.delete(watchersTable(existing.ccn),[existing.providerWatcherId]);else{const page=await db.list<WatcherRecord>(watchersTable(existing.ccn),{limit:100}),match=page.items.find(w=>w.userId===userId&&w.watchId===id);if(match)await db.delete(watchersTable(existing.ccn),[match.id]);}const remaining=await db.list<WatcherRecord>(watchersTable(existing.ccn),{limit:1});if(!remaining.items.length)await storage.delete([monitorPath(existing.ccn),statusPath(existing.ccn)]);return{deleted:true,id,ccn:existing.ccn};}
