import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowUpRight, BarChart3, Bell, Building2, CheckCircle2, Database, DollarSign, Home, LineChart, LoaderCircle, MapPinned, Network, RefreshCw, Save, Scale, Search, ShieldCheck, Stethoscope, Target, Trophy, X, Users } from 'lucide-react';
import { api } from './api';
import GlobalProviderSearch from './GlobalProviderSearch';
import IntelligenceCenter from './IntelligenceCenter';
import DecisionRoom from './DecisionRoom';
import TerritoryView from './TerritoryView';
import ReferralMarket from './ReferralMarket';
import DataLab from './DataLab';
import type { AnyRow, DashboardData, Provider, ProviderDetail, TabId, User } from './types';
import { solveGrowth } from './intelligenceMath';
import { apiError, clean, money, num, pct, STATES, statusClass, today } from './utils';
import { useAuth } from '@/context/AuthContext';

const NAV: Array<{ id: TabId; label: string; group: string; icon: typeof Home }> = [
  { id:'decision',label:'Decision Room',group:'DECIDE',icon:Target },{ id:'command',label:'Command Center',group:'DECIDE',icon:Home },
  { id:'intelligence',label:'Intelligence 360',group:'INTELLIGENCE',icon:LineChart },{ id:'hospice',label:'Hospice Explorer',group:'INTELLIGENCE',icon:Building2 },{ id:'compare',label:'Compare',group:'INTELLIGENCE',icon:Scale },{ id:'network',label:'Ownership / PECOS',group:'INTELLIGENCE',icon:Network },
  { id:'growth',label:'Growth Strategy',group:'GROWTH',icon:BarChart3 },{ id:'territory',label:'Territory',group:'GROWTH',icon:MapPinned },
  { id:'referral',label:'Referral Market',group:'ACCOUNTS',icon:Stethoscope },{ id:'watchlist',label:'Watchlist & Alerts',group:'ACCOUNTS',icon:Bell },{ id:'winloss',label:'Win / Loss',group:'ACCOUNTS',icon:Trophy },
  { id:'sources',label:'Data Lab',group:'DATA',icon:Database },
];

const parseHash = () => {
  const params = new URLSearchParams(window.location.hash.replace(/^#/, ''));
  const tab = params.get('tab') as TabId;
  return { state: (params.get('state') || 'OK').toUpperCase(), ccn: params.get('ccn') || '371653', tab: NAV.some((item) => item.id === tab) ? tab : 'command' as TabId };
};

export default function NationalDashboard() {
  const auth = useAuth();
  const initial = useMemo(parseHash, []);
  const [data, setData] = useState<DashboardData | null>(null);
  const [detail, setDetail] = useState<ProviderDetail | null>(null);
  const [state, setState] = useState(initial.state);
  const [focus, setFocus] = useState(initial.ccn);
  const [tab, setTab] = useState<TabId>(initial.tab);
  const [loading, setLoading] = useState(true);
  const [detailLoading, setDetailLoading] = useState(false);
  const [error, setError] = useState('');
  const user: User | null = auth.member ? { userId: String(auth.member.id), email: auth.member.email, name: auth.member.name, scope: 'Secure member workspace' } : null;
  const request = useRef({ market: 0, provider: 0 });

  const loadProvider = async (ccn: string, expectedState = state) => {
    if (!ccn) return;
    const id = ++request.current.provider;
    setFocus(ccn); setDetail(null); setDetailLoading(true); setError('');
    try {
      const response = await api.get(`/api/provider/${encodeURIComponent(ccn)}`), next = response.data as ProviderDetail;
      if (next.provider?.ccn !== ccn) throw new Error(`Provider context mismatch: requested ${ccn}, received ${next.provider?.ccn || 'no CCN'}.`);
      if (expectedState && next.provider?.state && String(next.provider.state).toUpperCase() !== expectedState.toUpperCase()) throw new Error(`Provider ${ccn} belongs to ${next.provider.state}, not the requested ${expectedState} market.`);
      if (id === request.current.provider) setDetail(next);
    } catch (requestError) {
      if (id === request.current.provider) setError(`Provider dossier refresh failed: ${apiError(requestError, 'The selected provider could not be loaded.')}`);
    } finally { if (id === request.current.provider) setDetailLoading(false); }
  };

  const loadMarket = async (nextState = state, requestedCcn = '', force = false) => {
    const id = ++request.current.market;
    setLoading(true); setError('');
    try {
      const response = await api.get(`/api/dashboard?state=${encodeURIComponent(nextState)}&ccn=${encodeURIComponent(requestedCcn)}${force ? '&force=1' : ''}`), next = response.data as DashboardData;
      if (id !== request.current.market) return;
      if (String(next.state).toUpperCase() !== nextState.toUpperCase()) throw new Error(`Market context mismatch: requested ${nextState}, received ${next.state || 'no state'}.`);
      if (!Array.isArray(next.providers) || next.providers.length === 0) throw new Error(`${next.stateName || nextState} returned no usable hospice providers. Retry the market refresh or choose another state.`);
      if (requestedCcn && next.focusCcn !== requestedCcn) throw new Error(`Provider ${requestedCcn} was not resolved inside the ${nextState} market.`);
      request.current.provider += 1;
      setData(next); setState(next.state); setFocus(next.focusCcn); setDetail(null);
      if (next.focusCcn) await loadProvider(next.focusCcn, next.state);
    } catch (requestError) { if (id === request.current.market) setError(apiError(requestError, 'CMS market refresh is temporarily unavailable.')); }
    finally { if (id === request.current.market) setLoading(false); }
  };

  useEffect(() => {
    void loadMarket(initial.state, initial.ccn);
  }, []);
  useEffect(() => { const params = new URLSearchParams({ state, ccn: focus, tab }); history.replaceState(null, '', `#${params.toString()}`); }, [state, focus, tab]);

  const signIn = () => setError('Your Spartan Elite session protects this workspace. Sign in again from the main account menu if access expires.');
  const providers = data?.providers || [];
  const providerValue = providers.some((provider) => provider.ccn === focus) ? focus : '';
  const providerPlaceholder = loading || detailLoading ? 'Loading providers…' : 'Select provider';
  const selected = data?.providers.find((provider) => provider.ccn === focus) || detail?.provider || data?.providers[0];
  const navigate = (next: TabId) => setTab(next);

  if (!data || !selected) return <div className={`boot ${error ? 'boot-error' : ''}`}>{error ? <AlertTriangle size={30}/> : <LoaderCircle className='spin' size={30}/>}<h2>{error ? 'Medicare Intelligence could not open this market' : 'Building national hospice intelligence...'}</h2><p>{error || 'Joining current CMS market and provider context.'}</p>{error ? <div className='boot-actions'><label className='market-picker'><span>Try another market</span><select aria-label='Recovery Medicare market' value={state} onChange={(event) => setState(event.target.value)}>{STATES.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select></label><button type='button' className='primary' onClick={() => void loadMarket(state, '', true)}>Retry market</button></div> : null}</div>;

  return <div className='app-shell'>
    <main className='main'>
      <header className='topbar'>
        <div className='page-title'><span>CMS MEDICARE INTELLIGENCE</span><h1>{NAV.find((item) => item.id === tab)?.label}</h1><p>National hospice evidence translated into decisions and field action.</p></div>
        <div className='topbar-workspace'><label className='market-picker'><span>Market</span><select aria-label='Select Medicare market' value={state} disabled={loading} onChange={(event) => void loadMarket(event.target.value)}>{STATES.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select></label><label className='market-picker'><span>Provider</span><select aria-label='Select Medicare provider' value={providerValue} disabled={loading || detailLoading || providers.length === 0} onChange={(event) => { if (!event.target.value) return; void loadProvider(event.target.value, state); }}><option value=''>{providerPlaceholder}</option>{providers.map((provider) => <option key={provider.ccn} value={provider.ccn}>{provider.name} · {provider.ccn}</option>)}</select></label><GlobalProviderSearch currentState={state} onOpen={(result) => { setTab('intelligence'); if (result.state !== state) { void loadMarket(result.state, result.ccn); return; } void loadProvider(result.ccn, state); }}/></div>
        <div className='topbar-actions'><button onClick={() => void loadMarket(state, focus, true)} disabled={loading}><RefreshCw size={16} className={loading ? 'spin' : ''}/><span>Refresh</span></button><button onClick={() => setTab('sources')} className={tab === 'sources' ? 'active' : ''}><Database size={16}/><span>Data health</span></button></div>
      </header>
      <div className='context-bar'><div><span className={`status-dot ${statusClass(data.dataQuality?.status)}`}/><span><small>ACTIVE PROVIDER</small><b>{selected.name}</b><em>{selected.city}, {selected.state} · CCN {selected.ccn}</em></span></div><div><small>MARKET</small><b>{data.stateName}</b></div><div><small>LAST REFRESH</small><b>{today()}</b></div></div>
      <nav className='workspace-nav' aria-label='Medicare Intelligence modules'>{NAV.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? 'active' : ''} aria-current={tab === id ? 'page' : undefined} onClick={() => setTab(id)}><Icon size={16}/><span>{label}</span></button>)}</nav>
      <div className='mobile-nav'><select aria-label='Choose Medicare Intelligence module' value={tab} onChange={(event) => setTab(event.target.value as TabId)}>{NAV.map((item) => <option key={item.id} value={item.id}>{item.group} · {item.label}</option>)}</select></div>
      {error && <div className='alert global-alert'><AlertTriangle size={17}/><span>{error}</span><button onClick={() => setError('')}><X size={14}/></button></div>}
      {data.warnings?.length > 0 && <div className='warning-strip'><AlertTriangle size={15}/><span><b>Source issue:</b> {data.warnings.join(' · ')} Successful evidence remains available.</span></div>}
      {tab === 'command' && <CommandPage data={data} provider={selected} detail={detail} onNavigate={navigate} onProvider={(ccn, providerState) => { void loadProvider(ccn, providerState || state); }}/>} 
      {tab === 'decision' && <DecisionRoom state={state} stateName={data.stateName} market={data} provider={selected} detail={detail} user={user} onSignIn={() => void signIn()} onNavigate={navigate}/>} 
      {tab === 'intelligence' && <IntelligenceCenter state={state} stateName={data.stateName} provider={selected} detail={detail} marketSources={data.sources} user={user} onSignIn={() => void signIn()} onOpenProvider={(ccn) => void loadProvider(ccn, state)}/>} 
      {tab === 'hospice' && <HospiceExplorer data={data} focus={focus} onProvider={(ccn) => void loadProvider(ccn, state)}/>} 
      {tab === 'compare' && <ComparePage data={data} focus={focus}/>} 
      {tab === 'network' && <OwnershipPage provider={selected} detail={detail}/>} 
      {tab === 'watchlist' && <WatchlistPage user={user} current={selected} onSignIn={() => void signIn()} onOpen={(ccn, providerState) => { setTab('intelligence'); if (providerState && providerState !== state) { void loadMarket(providerState, ccn); return; } void loadProvider(ccn, providerState || state); }}/>} 
      {tab === 'growth' && <GrowthPage data={data} provider={selected}/>} 
      {tab === 'territory' && <TerritoryView state={state} stateName={data.stateName} market={data} provider={selected} user={user} onSignIn={() => void signIn()}/>} 
      {tab === 'referral' && <ReferralMarket state={state} stateName={data.stateName} market={data}/>} 
      {tab === 'winloss' && <WinLossPage user={user} provider={selected} counties={data.counties} onSignIn={() => void signIn()}/>} 
      {tab === 'sources' && <DataLab state={state} provider={selected} providerStatus={String(detail?.dataQuality?.status || 'limited')}/>} 
    </main>
  </div>;
}

function CommandPage({ data, provider, detail, onNavigate }: { data: DashboardData; provider: Provider; detail: ProviderDetail | null; onNavigate: (tab: TabId) => void; onProvider: (ccn: string, providerState?: string) => void }) { const summary=data.marketSummary||{}; return <section className='page'><div className='hero'><div><span className='kicker'>NATIONAL COMMAND · {data.stateName.toUpperCase()}</span><h2>{provider.name}</h2><p>{provider.city}, {provider.state} · CCN {provider.ccn} · One operating picture from current CMS evidence.</p></div><div className='hero-actions'><button className='primary' onClick={()=>onNavigate('decision')}><Target size={15}/>Open Decision Room</button></div></div><div className='metrics six'><Metric icon={Building2} label='Hospices' value={num(data.providers.length)} sub='CMS-certified market'/><Metric icon={Users} label='Medicare lives' value={num(summary.totalMedicare)} sub='Market enrollment'/><Metric icon={Home} label='Focus ADC' value={num(provider.adc,1)} sub='Reported utilization'/><Metric icon={DollarSign} label='Focus payment' value={money(provider.payment)} sub='Reported Medicare'/><Metric icon={ShieldCheck} label='Evidence coverage' value={pct(detail?.confidence||data.dataQuality?.coveragePct,0)} sub={data.dataQuality?.status||'limited'}/><Metric icon={MapPinned} label='Counties' value={num(data.counties.length)} sub='Market geography'/></div><div className='launch-grid'><Launch icon={LineChart} label='Provider Intelligence 360' note='Quality, CAHPS, utilization, HCRIS, SSVI and service geography.' onClick={()=>onNavigate('intelligence')}/><Launch icon={MapPinned} label='Territory Deployment' note='See served, adjacent, hold and remote county posture.' onClick={()=>onNavigate('territory')}/><Launch icon={Stethoscope} label='Referral Market' note='Inspect hospitals, SNFs and serious-illness clinicians.' onClick={()=>onNavigate('referral')}/><Launch icon={Database} label='Data Lab' note='Validate source health, freshness and model completeness.' onClick={()=>onNavigate('sources')}/></div></section>; }
function HospiceExplorer({ data, focus, onProvider }: { data: DashboardData; focus: string; onProvider: (ccn: string) => void }) { const [query,setQuery]=useState(''); const rows=data.providers.filter(row=>`${row.name} ${row.city} ${row.county} ${row.ccn}`.toLowerCase().includes(query.toLowerCase())); return <section className='page'><div className='hero'><div><span className='kicker'>{data.stateName.toUpperCase()} CMS-CERTIFIED MARKET</span><h2>Hospice Explorer</h2><p>Find and open any enrolled hospice without losing market context.</p></div></div><div className='panel'><label className='local-search'><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search provider, city, county or CCN'/>{query&&<button onClick={()=>setQuery('')}><X size={14}/></button>}</label><div className='simple-table'><div className='simple-row header'><span>Provider</span><span>County</span><span>Ownership</span><span>ADC</span><span>Medicare payment</span></div>{rows.map(row=><button className={`simple-row ${row.ccn===focus?'selected':''}`} key={row.ccn} onClick={()=>onProvider(row.ccn)}><span><b>{row.name}</b><small>{row.city}, {row.state} · CCN {row.ccn}</small></span><span>{row.county||'NR'}</span><span>{row.ownership||'NR'}</span><span>{num(row.adc,1)}</span><span>{money(row.payment)}</span></button>)}</div></div></section>; }
function GrowthPage({ data, provider }: { data: DashboardData; provider: Provider }) { const [target,setTarget]=useState(Math.max(10,Math.round(Number(provider.adc)||25)+10)); const [los,setLos]=useState(Math.max(1,Math.round(Number(provider.daysPerBene)||75))); const [conversion,setConversion]=useState(50); const result=solveGrowth({currentAdc:Number(provider.adc)||0,targetAdc:target,losDays:los,conversionPct:conversion,horizonDays:90}); return <section className='page'><div className='hero'><div><span className='kicker'>90-DAY GROWTH STRATEGY · {data.stateName.toUpperCase()}</span><h2>Turn a census target into admissions and referral requirements.</h2><p>Transparent census-flow math. Change an assumption and the operating requirement recalculates immediately.</p></div></div><div className='panel'><div className='form-grid four'><label className='field'><span>Current ADC</span><input value={num(provider.adc,1)} disabled/></label><label className='field'><span>Target ADC</span><input type='number' value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label className='field'><span>Average length of stay</span><input type='number' value={los} onChange={e=>setLos(Number(e.target.value))}/></label><label className='field'><span>Referral conversion %</span><input type='number' value={conversion} onChange={e=>setConversion(Number(e.target.value))}/></label></div></div><div className='metrics five'><Metric icon={Target} label='Admissions / month' value={num(result.admissionsPerMonth,1)} sub='Required for target'/><Metric icon={Users} label='Referrals / month' value={num(result.referralsPerMonth,1)} sub={`At ${conversion}% conversion`}/><Metric icon={BarChart3} label='Referrals / week' value={num(result.referralsPerWeek,1)} sub='Weekly pace'/><Metric icon={LineChart} label='Referrals / workday' value={num(result.referralsPerWorkday,2)} sub='Daily requirement'/><Metric icon={Home} label='Natural census at day 90' value={num(result.projectedAdcWithoutAdmissions,1)} sub='Before new admissions'/></div><div className='panel'><p className='guardrail'>{result.formula} This planning model uses an exponential discharge assumption and should be reconciled to actual agency LOS and conversion history.</p></div></section>; }
function ComparePage({ data, focus }: { data: DashboardData; focus: string }) { const defaults=[focus,...data.providers.filter(p=>p.ccn!==focus).slice(0,2).map(p=>p.ccn)]; const [ids,setIds]=useState(defaults); const selected=ids.map(id=>data.providers.find(p=>p.ccn===id)).filter(Boolean) as Provider[]; return <section className='page'><div className='hero'><div><span className='kicker'>HEAD-TO-HEAD INTELLIGENCE</span><h2>Compare up to three hospices.</h2><p>Same market, same definitions, and missing values remain NR.</p></div></div><div className='panel'><div className='compare-picker'>{[0,1,2].map(index=><div key={index}><label>Provider {index+1}</label><select value={ids[index]||''} onChange={e=>setIds(current=>current.map((v,i)=>i===index?e.target.value:v))}><option value=''>Choose hospice</option>{data.providers.map(p=><option key={p.ccn} value={p.ccn}>{p.name} · {p.ccn}</option>)}</select></div>)}</div><div className='comparison-table'>{[['Provider',(p:Provider)=>p.name],['CCN',(p:Provider)=>p.ccn],['Location',(p:Provider)=>`${p.city}, ${p.state}`],['Ownership',(p:Provider)=>p.ownership||'NR'],['ADC',(p:Provider)=>num(p.adc,1)],['Beneficiaries',(p:Provider)=>num(p.beneficiaries)],['Days / beneficiary',(p:Provider)=>num(p.daysPerBene,1)],['Medicare payment',(p:Provider)=>money(p.payment)]].map(([label,get],index)=><div className={`compare-row ${index===0?'header':''}`} key={String(label)}><span>{String(label)}</span>{selected.map(p=><span key={p.ccn}>{(get as (p:Provider)=>string)(p)}</span>)}</div>)}</div></div></section>; }
function OwnershipPage({ provider, detail }: { provider: Provider; detail: ProviderDetail | null }) { return <section className='page'><div className='hero'><div><span className='kicker'>OWNERSHIP / PECOS CONTEXT</span><h2>{provider.name}</h2><p>Enrollment and ownership evidence is context, not proof of control beyond the published CMS record.</p></div></div><div className='grid-2'><div className='panel'><div className='panel-head'><div><span className='kicker'>OWNERS</span><h3>Published ownership records</h3></div><Network size={18}/></div><div className='entity-list'>{detail?.owners?.length?detail.owners.map((row,index)=><div key={index}><span><b>{clean(row.ownerName||row.name||row.organizationName)}</b><small>{clean(row.ownerType||row.type)} · {clean(row.role||row.association)}</small></span><em>{pct(row.percentageOwned||row.ownershipPercentage)}</em></div>):<p className='empty'>No current owner row was resolved for this CCN.</p>}</div></div><div className='panel'><div className='panel-head'><div><span className='kicker'>ENROLLMENT</span><h3>PECOS and certification context</h3></div></div><div className='entity-list'>{detail?.enrollments?.length?detail.enrollments.map((row,index)=><div key={index}><span><b>{clean(row.enrollmentId||row.associateId||`Enrollment ${index+1}`)}</b><small>{clean(row.enrollmentState||row.state)} · {clean(row.status)}</small></span></div>):<p className='empty'>No enrollment rows were resolved.</p>}</div></div></div></section>; }
function WatchlistPage({ user, current, onSignIn, onOpen }: { user: User | null; current: Provider; onSignIn: () => void; onOpen: (ccn: string, state: string) => void }) { const [records,setRecords]=useState<AnyRow[]>([]),[alerts,setAlerts]=useState<AnyRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''); const load=async()=>{try{const [w,a]=await Promise.all([api.get('/api/watchlist'),api.get('/api/alerts')]);setRecords(w.data.records||[]);setAlerts(a.data.records||a.data.alerts||[]);}catch(e){setError(apiError(e));}}; useEffect(()=>{if(user)void load();},[user?.userId]); const toggle=async()=>{if(!user)return onSignIn();setBusy(true);try{const found=records.find(r=>r.ccn===current.ccn);if(found)await api.delete(`/api/watchlist/${found.id}`);else await api.post('/api/watchlist',{ccn:current.ccn,state:current.state,label:current.name});await load();}catch(e){setError(apiError(e));}finally{setBusy(false);}}; const markRead=async(id:string)=>{try{await api.put(`/api/alerts/${id}`,{});setAlerts(currentAlerts=>currentAlerts.map(alert=>alert.id===id?{...alert,readAt:alert.readAt||new Date().toISOString()}:alert));}catch(e){setError(apiError(e,'Unable to mark alert as read.'));}}; return <section className='page'><div className='hero'><div><span className='kicker'>PRIVATE WATCHLIST</span><h2>Provider change intelligence</h2><p>Track material public-data changes and keep them tied to the right provider.</p></div><div className='hero-actions'><button className='primary' disabled={busy} onClick={()=>void toggle()}><Bell size={15}/>{records.some(r=>r.ccn===current.ccn)?'Remove focus provider':'Watch focus provider'}</button></div></div>{error&&<div className='alert'><AlertTriangle size={16}/>{error}</div>}<div className='grid-2'><div className='panel'><div className='panel-head'><div><span className='kicker'>{records.length} WATCHED</span><h3>Provider watchlist</h3></div></div>{records.length?records.map(row=><div className='watch-row' key={row.id}><button onClick={()=>onOpen(row.ccn,row.state)}><span className='rank'><Bell size={14}/></span><span><b>{row.label}</b><small>{row.state} · CCN {row.ccn}</small></span><em>{row.monitor?.lastStatus||'MONITORING'}</em></button></div>):<p className='empty'>No providers watched yet.</p>}</div><div className='panel'><div className='panel-head'><div><span className='kicker'>{alerts.length} ALERTS</span><h3>Change ledger</h3></div></div>{alerts.length?alerts.map(row=><div className='change-list' key={row.id}><div><span>{row.severity||'CHANGE'}</span><p><b>{row.providerLabel}</b>{row.summary}</p></div>{!row.readAt?<button type='button' className='ghost' onClick={()=>void markRead(String(row.id))}>Mark read</button>:<em>Read</em>}</div>):<p className='empty'>No provider changes detected.</p>}</div></div></section>; }
function WinLossPage({ user, provider, counties, onSignIn }: { user: User | null; provider: Provider; counties: AnyRow[]; onSignIn: () => void }) { const [records,setRecords]=useState<AnyRow[]>([]),[summary,setSummary]=useState<AnyRow>({}),[account,setAccount]=useState(''),[outcome,setOutcome]=useState('Win'),[reason,setReason]=useState('Relationship'),[busy,setBusy]=useState(false); const load=async()=>{const r=await api.get(`/api/winloss?ccn=${provider.ccn}`);setRecords(r.data.records||[]);setSummary(r.data.summary||{});}; useEffect(()=>{if(user)void load();},[user?.userId,provider.ccn]); const save=async()=>{if(!user)return onSignIn();if(!account.trim())return;setBusy(true);try{await api.post('/api/winloss',{providerCcn:provider.ccn,date:today(),outcome,account,reason,county:counties[0]?.name||'',accountType:'Other',notes:'',estimatedMonthlyReferrals:0});setAccount('');await load();}finally{setBusy(false);}}; return <section className='page'><div className='hero'><div><span className='kicker'>PRIVATE FIELD INTELLIGENCE · {provider.name}</span><h2>Win / Loss</h2><p>Turn field outcomes into a usable pattern, not a stack of anecdotes.</p></div></div><div className='metrics'><Metric icon={Trophy} label='Win rate' value={pct(summary.winRate)} sub={`${num(summary.total)} decisions`}/><Metric icon={CheckCircle2} label='Wins' value={num(summary.wins)} sub={summary.topWinReason||'Not enough data'}/><Metric icon={X} label='Losses' value={num(summary.losses)} sub={summary.topLossReason||'Not enough data'}/><Metric icon={Users} label='Monthly referrals won' value={num(summary.estimatedMonthlyWon)} sub='Estimated'/></div><div className='grid-2'><div className='panel'><div className='panel-head'><div><span className='kicker'>RECORD OUTCOME</span><h3>Add field intelligence</h3></div></div><div className='form-grid'><label className='field wide'><span>Account</span><input value={account} onChange={e=>setAccount(e.target.value)} placeholder='Account or referral source'/></label><label className='field'><span>Outcome</span><select value={outcome} onChange={e=>setOutcome(e.target.value)}><option>Win</option><option>Loss</option></select></label><label className='field'><span>Primary reason</span><input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className='primary wide' disabled={busy||!account.trim()} onClick={()=>void save()}><Save size={15}/>Save outcome</button></div></div><div className='panel'><div className='panel-head'><div><span className='kicker'>DECISION HISTORY</span><h3>Latest outcomes</h3></div></div><div className='entity-list'>{records.length?records.map(row=><div key={row.id}><span><b>{row.account}</b><small>{row.date} · {row.reason}</small></span><em>{row.outcome}</em></div>):<p className='empty'>No outcomes recorded for this provider.</p>}</div></div></div></section>; }
function Metric({ icon: Icon, label, value, sub }: { icon: typeof Users; label: string; value: string; sub: string }) { return <div className='metric'><Icon size={17}/><span>{label}</span><b>{value}</b><small>{sub}</small></div>; }
function Launch({ icon: Icon, label, note, onClick }: { icon: typeof Home; label: string; note: string; onClick: () => void }) { return <button className='launch-card' onClick={onClick}><Icon size={20}/><b>{label}</b><p>{note}</p></button>; }
