import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Building2, LoaderCircle, Stethoscope, UserRoundSearch } from 'lucide-react';
import { api } from './api';
import type { AnyRow, DashboardData } from './types';
import { apiError, money, num, pct } from './utils';

export default function ReferralMarket({ state, stateName, market }: { state: string; stateName: string; market: DashboardData }) {
  const [view, setView] = useState<'hospitals'|'snfs'|'physicians'>('hospitals');
  const [physicians, setPhysicians] = useState<AnyRow[]>([]);
  const [physicianMeta, setPhysicianMeta] = useState<AnyRow>({});
  const [physicianLoading, setPhysicianLoading] = useState(false);
  const [hospital, setHospital] = useState<AnyRow | null>(null);
  const [hospitalLoading, setHospitalLoading] = useState(false);
  const [physician, setPhysician] = useState<AnyRow | null>(null);
  const [physicianDetailLoading, setPhysicianDetailLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => { setPhysicians([]); setPhysicianMeta({}); setHospital(null); setPhysician(null); setError(''); }, [state]);
  useEffect(() => {
    if (view !== 'physicians' || physicians.length || physicianLoading) return;
    setPhysicianLoading(true);
    void api.get(`/api/physicians/${encodeURIComponent(state)}`).then((response) => { setPhysicians(response.data.physicians || []); setPhysicianMeta(response.data); }).catch((requestError) => setError(apiError(requestError, 'Clinician opportunity could not be loaded.'))).finally(() => setPhysicianLoading(false));
  }, [view, state, physicians.length, physicianLoading]);

  const hospitals = useMemo(() => [...(market.hospitals || [])].sort((a, b) => String(a.name).localeCompare(String(b.name))), [market.hospitals]);
  const snfs = useMemo(() => [...(market.snfs || [])].sort((a, b) => Number(b.score ?? -1) - Number(a.score ?? -1)), [market.snfs]);
  const openHospital = async (ccn: string) => { setHospitalLoading(true); setError(''); try { const response = await api.get(`/api/hospital/${encodeURIComponent(ccn)}`); setHospital(response.data); } catch (requestError) { setError(apiError(requestError, 'Hospital detail could not be loaded.')); } finally { setHospitalLoading(false); } };
  const openPhysician = async (npi: string) => { setPhysicianDetailLoading(true); setError(''); try { const response = await api.get(`/api/physician/${encodeURIComponent(npi)}`); setPhysician(response.data); } catch (requestError) { setError(apiError(requestError, 'Physician 360 could not be loaded.')); } finally { setPhysicianDetailLoading(false); } };

  return <section className='page'>
    <div className='hero'><div><span className='kicker'>REFERRAL MARKET · {stateName.toUpperCase()}</span><h2>Follow the accounts that can change the referral conversation.</h2><p>Hospitals, SNFs and serious-illness clinicians are prospecting and education context. Volume does not establish patient-level hospice eligibility.</p></div><div className='segmented'><button className={view === 'hospitals' ? 'active' : ''} onClick={() => setView('hospitals')}>Hospitals</button><button className={view === 'snfs' ? 'active' : ''} onClick={() => setView('snfs')}>SNFs</button><button className={view === 'physicians' ? 'active' : ''} onClick={() => setView('physicians')}>Physicians</button></div></div>
    {error && <div className='alert'><AlertTriangle size={16}/>{error}</div>}

    {view === 'hospitals' && <div className='grid-2'><div className='panel'><div className='panel-head'><div><span className='kicker'>{hospitals.length} HOSPITALS</span><h3>Acute referral market</h3><p>Open a facility to inspect CMS service-area and inpatient DRG context.</p></div><Building2 size={18}/></div><div className='rank-table'>{hospitals.map((row: AnyRow, index) => <button key={row.ccn} onClick={() => void openHospital(row.ccn)}><span className='rank'>{String(index + 1).padStart(2, '0')}</span><span><b>{row.name}</b><small>{row.city} · {row.county || 'County NR'} · CCN {row.ccn}</small></span><em>{row.rating ? `${row.rating} rating` : 'OPEN'}</em></button>)}</div></div><div className='panel sticky-detail'>{hospitalLoading ? <p className='loading'><LoaderCircle className='spin' size={18}/>Loading hospital evidence...</p> : hospital ? <><div className='panel-head'><div><span className='kicker'>HOSPITAL 360</span><h3>{hospital.hospital?.name}</h3><p>{hospital.hospital?.city}, {hospital.hospital?.state} · CCN {hospital.hospital?.ccn}</p></div></div><div className='kpi-grid'><div><span>Service-area cases</span><b>{num(hospital.summary?.totalCases)}</b></div><div><span>Inpatient discharges</span><b>{num(hospital.summary?.totalInpatientDischarges)}</b></div><div><span>Serious-illness DRG discharges</span><b>{num(hospital.summary?.hospiceRelevantDischarges)}</b></div><div><span>Serious-illness share</span><b>{pct(hospital.summary?.hospiceRelevantSharePct)}</b></div><div><span>Service-area days</span><b>{num(hospital.summary?.totalDays)}</b></div><div><span>Service-area charges</span><b>{money(hospital.summary?.totalCharges)}</b></div></div><h4 className='subhead'>Hospice-relevant discharge-planning context</h4><div className='entity-list'>{(hospital.hospiceRelevant || []).slice(0, 18).map((row: AnyRow) => <div key={`${row.drg}-${row.description}`}><span><b>{row.description}</b><small>DRG {row.drg}</small></span><em>{num(row.discharges)} discharges</em></div>)}</div><p className='guardrail'>Serious-illness DRGs are discharge-planning context. They do not establish hospice eligibility for any patient.</p></> : <p className='empty'>Select a hospital to inspect its public Medicare referral context.</p>}</div></div>}

    {view === 'snfs' && <div className='panel'><div className='panel-head'><div><span className='kicker'>{snfs.length} SKILLED NURSING FACILITIES</span><h3>SNF opportunity board</h3><p>Confidence-adjusted prospecting priority using reported resident census and certified beds.</p></div><Building2 size={18}/></div><div className='simple-table'><div className='simple-row header'><span>Facility</span><span>Residents</span><span>Beds</span><span>Occupancy</span><span>Rating</span><span>Opportunity</span></div>{snfs.map((row: AnyRow) => <div className='simple-row six-cols' key={row.ccn}><span><b>{row.name}</b><small>{row.city} · {row.county} · CCN {row.ccn}</small></span><span>{num(row.residents,1)}</span><span>{num(row.beds)}</span><span>{pct(row.occupancyPct)}</span><span>{num(row.rating,1)}</span><span><strong>{num(row.score)}/100</strong><small>{num(row.opportunityCoveragePct)}% evidence</small></span></div>)}</div><p className='guardrail'>Facility census is prospecting scale. It is never evidence that an individual resident qualifies for hospice.</p></div>}

    {view === 'physicians' && <div className='grid-2'><div className='panel'><div className='panel-head'><div><span className='kicker'>PHYSICIAN OPPORTUNITY 3.0</span><h3>{stateName} clinician priorities</h3><p>Specialty-peer Medicare panel, serious-illness burden, service intensity and hospice relevance.</p></div>{physicianLoading ? <LoaderCircle className='spin' size={18}/> : <UserRoundSearch size={18}/>}</div>{physicianMeta?.partial && <div className='scope-note'><AlertTriangle size={14}/>The live state clinician scan hit its configured row ceiling. The ranking is scoped until the checkpointed warehouse completes.</div>}<div className='rank-table'>{physicians.slice(0, 100).map((row, index) => <button key={row.npi} onClick={() => void openPhysician(row.npi)}><span className='rank'>{String(index + 1).padStart(2, '0')}</span><span><b>{row.name}</b><small>{row.specialty} · {row.city} · {row.county || row.zip} · {num(row.beneficiaries)} Medicare beneficiaries</small></span><em>{num(row.score)}/100</em></button>)}{physicianLoading && !physicians.length && <p className='loading'><LoaderCircle className='spin' size={18}/>Building state clinician ranking...</p>}</div></div><div className='panel sticky-detail'>{physicianDetailLoading ? <p className='loading'><LoaderCircle className='spin' size={18}/>Loading Physician 360...</p> : physician ? <><div className='panel-head'><div><span className='kicker'>PHYSICIAN 360</span><h3>{physician.profile?.name || physician.npi}</h3><p>{physician.profile?.specialty || 'Specialty NR'} · NPI {physician.npi}</p></div><Stethoscope size={18}/></div><div className='kpi-grid'><div><span>Medicare beneficiaries</span><b>{num(physician.profile?.beneficiaries)}</b></div><div><span>Services</span><b>{num(physician.summary?.totalServices)}</b></div><div><span>Hospice refer eligibility</span><b>{physician.eligibility?.hospice?.raw || 'NR'}</b></div><div><span>Part B eligibility</span><b>{physician.eligibility?.partB?.raw || 'NR'}</b></div></div><h4 className='subhead'>Top provider + service rows</h4><div className='entity-list'>{(physician.services || []).slice(0, 20).map((row: AnyRow, index: number) => <div key={`${row.hcpcs}-${row.placeOfService}-${index}`}><span><b>{row.description || row.hcpcs}</b><small>HCPCS {row.hcpcs} · POS {row.placeOfService}</small></span><em>{num(row.services)} services</em></div>)}</div><p className='guardrail'>{physician.caveat}</p></> : <p className='empty'>Select a clinician to inspect Provider + Service and Order/Referring evidence.</p>}</div></div>}
  </section>;
}
